Repository shipwright-io/build, pull requests merged in 2020-04, with the labels that each got.

#92 Add resource limit support
  README.md
  deploy/crds/build.dev_buildruns_crd.yaml
  deploy/crds/build.dev_builds_crd.yaml
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
  samples/build/build_buildpacks-v3_namespaced_cr.yaml
  samples/build/build_kaniko_cr.yaml
  samples/buildrun/buildrun_buildah_cr.yaml
  samples/buildrun/buildrun_kaniko_cr.yaml
  test/e2e/main_test.go
  test/e2e/validators.go
Labels: approved, lgtm

#93 Add detail capabilities in buildstrategy yamls
  samples/buildrun/buildrun_buildah_cr.yaml
  samples/buildrun/buildrun_kaniko_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
Labels: approved, lgtm

#87 Add env variables for the e2e tests
  HACK.md
  test/data/build_buildah_cr_private_github.yaml
  test/data/build_buildah_cr_private_gitlab.yaml
  test/data/build_buildpacks-v3_cr_private_github.yaml
  test/data/build_kaniko_cr_private_github.yaml
  test/data/build_kaniko_cr_private_gitlab.yaml
  test/data/build_source-to-image_cr_private_github.yaml
  test/e2e/buildah_test.go
  test/e2e/buildpacks_namespaced_test.go
  test/e2e/buildpacks_test.go
  test/e2e/kaniko_test.go
  test/e2e/main_test.go
  test/e2e/s2i_test.go
  test/e2e/validators.go
Labels: approved, lgtm, ok-to-test

#107 Installs the ginkgo CLI and the matcher library
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#102 Consolidate context directory for Kaniko and BuildAh
  README.md
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
  samples/build/build_kaniko_cr.yaml
  samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  test/data/build_buildah_cr_custom_context+dockerfile.yaml
  test/data/build_kaniko_cr_custom_context+dockerfile.yaml
  test/data/build_kaniko_cr_private_github.yaml
  test/data/build_kaniko_cr_private_gitlab.yaml
  test/data/buildrun_buildah_cr_custom_context+dockerfile.yaml
  test/data/buildrun_kaniko_cr_custom_context+dockerfile.yaml
  test/e2e/main_test.go
  test/e2e/validators.go
Labels: approved, lgtm, ok-to-test

#99 Validate during Build creation the following:
  .gitignore
  .travis.yml
  HACK.md
  Makefile
  deploy/crds/build.dev_builds_crd.yaml
  go.mod
  go.sum
  hack/generate-fakes.sh
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildstrategy_types.go
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/build/build_suite_test.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/fakes/client.go
  pkg/controller/fakes/manager.go
  pkg/controller/fakes/status_writer.go
  pkg/controller/suite_test.go
  test/catalog.go
Labels: approved, lgtm, ok-to-test

#119 Add missing Reason column to the Build controller
  deploy/crds/build.dev_builds_crd.yaml
  pkg/apis/build/v1alpha1/build_types.go
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  test/catalog.go
Labels: approved, lgtm, needs-ok-to-test

#122 Add Jordan as approver
  OWNERS
Labels: approved, do-not-merge/invalid-owners-file, lgtm

#105 Enhance the ServiceAccount generation and check logic in BuildRun controller
  README.md
  deploy/crds/build.dev_buildruns_crd.yaml
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/generate_taskrun_test.go
  samples/buildrun/buildrun_buildpacks-v3_cr.yaml
  samples/buildrun/buildrun_buildpacks-v3_namespaced_cr.yaml
  samples/buildrun/buildrun_kaniko_cr.yaml
  samples/buildrun/buildrun_source-to-image_cr.yaml
Labels: approved, lgtm

#137 Add sample script to get logs of buildrun
  hack/build-logs.sh
Labels: approved, lgtm

#118 Add dependency on SETGID and SETUID for Kaniko
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  test/data/build_kaniko_cr_advanced_dockerfile.yaml
  test/data/buildrun_kaniko_cr_advanced_dockerfile.yaml
  test/e2e/main_test.go
Labels: approved, lgtm, ok-to-test

#130 Create LICENSE
  LICENSE
Labels: approved, lgtm

#145 Add +kubebuilder for build CRD
  deploy/crds/build.dev_builds_crd.yaml
  pkg/apis/build/v1alpha1/build_types.go
Labels: approved, lgtm, ok-to-test

#152 fix BuildStrategyKind is nil issue
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  test/catalog.go
Labels: approved, lgtm, needs-ok-to-test

#121 External Container Registry for E2E
  .travis.yml
  HACK.md
  Makefile
  hack/install-operator-sdk.sh
  test/e2e/main_test.go
  test/e2e/operator.go
  test/e2e/samples.go
  test/e2e/validators.go
Labels: approved, lgtm

#155 Rewrite test case for credentials to Ginkgo
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_suite_test.go
  pkg/controller/buildrun/credential_test.go
  pkg/controller/buildrun/credentials.go
  pkg/controller/buildrun/credentials_test.go
Labels: approved, lgtm, ok-to-test

#142 Improve Build repo docs
  README.md
  docs/README.md
  docs/build.md
  docs/buildrun.md
  docs/buildstrategies.md
  docs/controllers_flow.png
  samples/buildstrategy/buildah/README.md
  samples/buildstrategy/buildpacks-v3/README.md
  samples/buildstrategy/kaniko/README.md
  samples/buildstrategy/source-to-image/README.md
Labels: lgtm, ok-to-test

#162 Local Container Registry
  .travis.yml
  HACK.md
  Makefile
  hack/install-kind.sh
  hack/install-kubectl.sh
  hack/install-registry.sh
Labels: approved, lgtm, ok-to-test

#164 Add a new reviewer
  OWNERS
Labels: approved, do-not-merge/invalid-owners-file, ok-to-test

#153 Add failure status for buildRun
  pkg/controller/build/build_controller.go
  pkg/controller/buildrun/buildrun_controller.go
Labels: approved, lgtm
