Repository shipwright-io/build, pull requests merged in 2020-08, with the labels that each got.

#326 Add documentation for KANIKO_CONTAINER_IMAGE env var
  docs/build.md
Labels: lgtm

#323 Rollback to use a generated name for each TaskRun
  pkg/controller/build/build_controller.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
  test/catalog.go
Labels: approved, lgtm, ok-to-test

#328 Add some code enhancements
  Makefile
  pkg/controller/build/build_controller.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/runtime_image_test.go
  test/catalog.go
  test/e2e/e2e_suite_test.go
  test/e2e/ginkgo_operator-sdk.go
  test/e2e/validators.go
Labels: approved, lgtm

#334 Remove leader-for-life HA mode
  cmd/manager/main.go
Labels: lgtm, ok-to-test

#335 Remove packages for the leader election
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/doc.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/leader.go
  vendor/modules.txt
Labels: approved, lgtm

#331 Retrieve build in buildrun controller only to create taskrun
  Makefile
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  test/catalog.go
Labels: approved, lgtm

#339 Do not perform any logic for completed BuildRuns
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
Labels: approved, lgtm

#343 Delay taskrun creation if build is not yet validated
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
Labels: approved, lgtm

#342 Make timeouts within e2e tests configurable
  HACK.md
  Makefile
  test/e2e/validators.go
Labels: approved, lgtm

#309 Proposal: Local Registry Image Specs
  docs/proposals/local-registry-image-specs.md
Labels: approved, lgtm

#344 set package refs as shipwright-io/build
  .travis.yml
  Dockerfile
  HACK.md
  Makefile
  README.md
  cmd/manager/main.go
  docs/development/deploying.md
  docs/proposals/runtime-image.md
  go.mod
  openshift-ci/Dockerfile.tools
  pkg/apis/addtoscheme_build_v1alpha1.go
  pkg/apis/core/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_build.go
  pkg/controller/add_buildrun.go
  pkg/controller/add_buildstrategy.go
  pkg/controller/add_clusterbuildstrategy.go
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  pkg/controller/buildrun/credentials.go
  pkg/controller/buildrun/credentials_test.go
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
  pkg/controller/buildrun/runtime_image.go
  pkg/controller/buildrun/runtime_image_test.go
  pkg/controller/buildstrategy/buildstrategy_controller.go
  pkg/controller/buildstrategy/buildstrategy_controller_test.go
  pkg/controller/clusterbuildstrategy/clusterbuildstrategy_controller.go
  pkg/controller/clusterbuildstrategy/clusterbuildstrategy_controller_test.go
  pkg/controller/controller.go
  pkg/controller/utils/utils.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  test/catalog.go
  test/e2e/e2e_test.go
  test/e2e/ginkgo_operator-sdk.go
  test/e2e/samples.go
  test/e2e/validators.go
Labels: approved, lgtm

#349 Change delay logic to use an error
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
Labels: approved, lgtm

#351 Fix badge for travis and add new ones
  README.md
Labels: approved, lgtm

#352 Remove reference to a service account on auto-generation
  samples/buildrun/buildrun_buildah_cr.yaml
  samples/buildrun/buildrun_buildpacks-v3-heroku_cr.yaml
  samples/buildrun/buildrun_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildrun/buildrun_buildpacks-v3_cr.yaml
  samples/buildrun/buildrun_buildpacks-v3_namespaced_cr.yaml
  test/data/buildrun_buildpacks-v3_nodejs_runtime-image_cr.yaml
Labels: approved, lgtm

#361 Retry RPC error
  test/e2e/validators.go
Labels: approved, lgtm

#362 Fix PathContext to ContextDir
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
  test/buildstrategy_samples.go
Labels: approved, lgtm

#363 Initial Release Pipeline
  .travis.yml
  Makefile
  hack/release.sh
Labels: approved, lgtm
