Repository shipwright-io/build, pull requests merged in 2020-03, with the labels that each got.

#27 Readme changes and update to BuildStrategies
  HACK.md
  README.md
  hack/crd.sh
  pkg/controller/build/build_controller.go
  samples/build/build_buildah_cr.yaml
  samples/build/build_buildpacks-v3_cr.yaml
  samples/build/build_kaniko_cr.yaml
  samples/build/build_source-to-image_cr.yaml
  samples/buildstrategy/buildah/README.md
  samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
  samples/buildstrategy/buildpacks-v3/README.md
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildstrategy_buildah_cr.yaml
  samples/buildstrategy/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/kaniko/README.md
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/source-to-image/README.md
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
Labels: approved, lgtm, size/XL

#37 Add private output image to roadmap
  README.md
Labels: size/XS

#35 Travis-CI for unit tests
  .travis.yml
  Makefile
  hack/install-kind.sh
  hack/install-operator-sdk.sh
  hack/install-tekton.sh
Labels: approved, lgtm, size/L

#42 Add test for buildpacks
  deploy/crds/build.dev_builds_crd.yaml
  go.mod
  go.sum
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/gitsource.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/build/generate_tekton.go
  samples/build/build_buildpacks-v3_cr.yaml
  test/e2e/build_test.go
  test/e2e/buildah_test.go
  test/e2e/buildpack_test.go
  test/e2e/main_test.go
  vendor/k8s.io/api/admission/v1/doc.go
  vendor/k8s.io/api/admission/v1/generated.pb.go
  vendor/k8s.io/api/admission/v1/generated.proto
  vendor/k8s.io/api/admission/v1/register.go
  vendor/k8s.io/api/admission/v1/types.go
  vendor/k8s.io/api/admission/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/admission/v1/zz_generated.deepcopy.go
  vendor/k8s.io/api/imagepolicy/v1alpha1/doc.go
  vendor/k8s.io/api/imagepolicy/v1alpha1/generated.pb.go
  vendor/k8s.io/api/imagepolicy/v1alpha1/generated.proto
  vendor/k8s.io/api/imagepolicy/v1alpha1/register.go
  vendor/k8s.io/api/imagepolicy/v1alpha1/types.go
  vendor/k8s.io/api/imagepolicy/v1alpha1/types_swagger_doc_generated.go
  vendor/k8s.io/api/imagepolicy/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/kubectl/LICENSE
  vendor/k8s.io/kubectl/pkg/scheme/install.go
  vendor/k8s.io/kubectl/pkg/scheme/scheme.go
  vendor/modules.txt
Labels: size/XXL

#43 Steps to do a buildpacks-v3 build
  samples/buildstrategy/buildpacks-v3/README.md
Labels: size/M

#44 Add e2e tests for all Build & BuildStragegy CRs in the samples
  test/e2e/buildah_test.go
  test/e2e/buildpack_test.go
  test/e2e/kaniko_test.go
  test/e2e/main_test.go
  test/e2e/s2i_test.go
  test/e2e/validators.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: size/XXL

#38 Support credentials for builder images
  README.md
  deploy/crds/build.dev_builds_crd.yaml
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/build/credential_test.go
  pkg/controller/build/credentials.go
  pkg/controller/build/generate_tekton.go
  pkg/controller/build/generate_tekton_test.go
  samples/build/build_buildpacks-v3_cr.yaml
  samples/build/build_source-to-image_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/e2e/main_test.go
Labels: approved, lgtm, size/L

#60 Fix the services typo in .travis.yml
  .travis.yml
Labels: approved, lgtm, ok-to-test, size/XS

#61 Add unit test for getCustomTaskRun
  .gitignore
  pkg/apis/build/v1alpha1/build_types.go
  pkg/controller/build/credential_test.go
  pkg/controller/build/generate_tekton.go
  pkg/controller/build/generate_tekton_test.go
Labels: approved, lgtm, ok-to-test, size/L

#63 Add tekton resource permissions for operator rbac role
  deploy/role.yaml
Labels: approved, lgtm, ok-to-test, size/S

#68 Change to cluster-scope operator
  cmd/manager/main.go
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, ok-to-test, size/S

#69 Add missing CRD file reference
  hack/crd.sh
Labels: approved, lgtm, ok-to-test, size/XS

#73 Solve the unstructured.Unstructured error message in controller log
  cmd/manager/main.go
Labels: approved, lgtm, ok-to-test

#36 changes to readme
  README.md
Labels: approved, lgtm, size/XS

#72 Change the default BuildStrategy in doc and test to cluster scope
  README.md
  deploy/role.yaml
  hack/crd.sh
  samples/build/build_buildah_cr.yaml
  samples/build/build_buildpacks-v3_cr.yaml
  samples/build/build_buildpacks-v3_namespaced_cr.yaml
  samples/build/build_kaniko_cr.yaml
  samples/build/build_source-to-image_cr.yaml
  samples/buildstrategy/buildah/README.md
  samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
  samples/buildstrategy/buildpacks-v3/README.md
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
  samples/buildstrategy/kaniko/README.md
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/source-to-image/README.md
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/e2e/buildah_test.go
  test/e2e/buildpacks_clusterbuildstrategy_test.go
  test/e2e/buildpacks_namespaced_test.go
  test/e2e/buildpacks_test.go
  test/e2e/kaniko_test.go
  test/e2e/main_test.go
  test/e2e/s2i_test.go
  test/e2e/validators.go
Labels: approved, lgtm, ok-to-test

#78 Separate build definition from build run
  README.md
  deploy/crds/build.dev_buildruns_crd.yaml
  deploy/crds/build.dev_builds_crd.yaml
  deploy/crds/build.dev_buildstrategies_crd.yaml
  deploy/crds/build.dev_clusterbuildstrategies_crd.yaml
  deploy/role.yaml
  hack/crd.sh
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/buildstrategy_types.go
  pkg/apis/build/v1alpha1/clusterbuildstrategy_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha1/condition_types.go
  pkg/apis/core/v1alpha1/volatile_time.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_buildrun.go
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/credential_test.go
  pkg/controller/buildrun/credentials.go
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
  samples/build/build_buildpacks-v3_namespaced_cr.yaml
  samples/buildrun/buildrun_buildah_cr.yaml
  samples/buildrun/buildrun_buildpacks-v3_cr.yaml
  samples/buildrun/buildrun_buildpacks-v3_namespaced_cr.yaml
  samples/buildrun/buildrun_kaniko_cr.yaml
  samples/buildrun/buildrun_source-to-image_cr.yaml
  samples/buildstrategy/buildpacks-v3/README.md
  test/e2e/buildah_test.go
  test/e2e/buildpacks_namespaced_test.go
  test/e2e/buildpacks_test.go
  test/e2e/kaniko_test.go
  test/e2e/main_test.go
  test/e2e/s2i_test.go
  test/e2e/validators.go
Labels: approved, lgtm, ok-to-test

#79 Refine the operator name in Makefile
  Makefile
Labels: approved, lgtm, ok-to-test

#81 Refine the Dockerfile in root folder
  Dockerfile
Labels: approved, lgtm, ok-to-test

#86 Refine the secret name in Build example yaml
  README.md
Labels: approved, lgtm

#85 Add revision support for Git source
  deploy/crds/build.dev_builds_crd.yaml
  pkg/apis/build/v1alpha1/gitsource.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
  samples/build/build_buildah_cr.yaml
Labels: approved, lgtm
