Repository shipwright-io/build, pull requests merged in 2020-07, with the labels that each got.

#235 Add basic custom metrics support
  cmd/manager/main.go
  docs/metrics.md
  go.mod
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_suite_test.go
  pkg/metrics/metrics_test.go
  test/catalog.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
  vendor/modules.txt
Labels: Release 0.1.x, approved, lgtm

#287 Working Directory Attribute
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
Labels: approved, lgtm

#286 Update Kaniko to 0.24.0, use new snapshotMode
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
Labels: Release 0.1.x, approved, lgtm

#293 Fix the nil pointer error when builder controller is restarted
  pkg/controller/buildrun/buildrun_controller.go
Labels: Release 0.1.x, approved, lgtm

#294 Bring ruby e2e test back
  test/e2e/e2e_test.go
Labels: approved, ok-to-test

#271 Add proposal on how to handle resource assignments to strategy steps for issue #239
  docs/proposals/buildstrategy-steps-resources.md
Labels: Release 0.1.x, lgtm

#291 Move the steps resources definition into the strategies
  deploy/crds/build.dev_buildruns_crd.yaml
  deploy/crds/build.dev_builds_crd.yaml
  docs/build.md
  docs/buildrun.md
  docs/buildstrategies.md
  go.mod
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
  samples/build/build_buildpacks-v3-heroku_cr.yaml
  samples/build/build_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/build/build_buildpacks-v3_cr.yaml
  samples/build/build_buildpacks-v3_namespaced_cr.yaml
  samples/build/build_kaniko_cr.yaml
  samples/buildrun/buildrun_buildah_cr.yaml
  samples/buildrun/buildrun_kaniko_cr.yaml
  samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  test/build_samples.go
  test/buildrun_samples.go
  test/buildstrategy_samples.go
  test/catalog.go
  test/data/build_buildpacks-v3-heroku_cr_private_github.yaml
  test/data/build_buildpacks-v3_cr_private_github.yaml
  test/data/build_buildpacks-v3_golang_cr.yaml
  test/data/build_buildpacks-v3_java_cr.yaml
  test/data/build_buildpacks-v3_php_cr.yaml
  test/data/build_buildpacks-v3_ruby_cr.yaml
  test/data/build_kaniko_cr_advanced_dockerfile.yaml
  test/data/build_timeout.yaml
Labels: Release 0.1.x, approved, lgtm, ok-to-test

#263 Runtime Image Support
  cmd/manager/main.go
  deploy/crds/build.dev_buildruns_crd.yaml
  deploy/crds/build.dev_builds_crd.yaml
  deploy/crds/build.dev_buildstrategies_crd.yaml
  deploy/crds/build.dev_clusterbuildstrategies_crd.yaml
  docs/build.md
  docs/proposals/runtime-image.md
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/config/config.go
  pkg/controller/build/build_controller.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
  pkg/controller/buildrun/runtime_image.go
  pkg/controller/buildrun/runtime_image_test.go
  pkg/controller/utils/utils.go
  test/data/build_buildpacks-v3_nodejs_runtime-image_cr.yaml
  test/data/buildrun_buildpacks-v3_nodejs_runtime-image_cr.yaml
  test/e2e/e2e_test.go
Labels: approved, lgtm, runtime-base-image

#298 Refine build_buildrun_establish_duration_seconds buckets and make buckets configurable
  Makefile
  docs/metrics.md
  pkg/config/config.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: Release 0.1.x, approved, lgtm

#297 Adding Adam and Gabe to OWNERS.
  OWNERS
Labels: approved

#299 Drop containers `protocol` from "required"
  deploy/crds/build.dev_buildstrategies_crd.yaml
  deploy/crds/build.dev_clusterbuildstrategies_crd.yaml
Labels: approved, lgtm, ok-to-test

#304 Owners update
  OWNERS
Labels: approved, do-not-merge/invalid-owners-file, lgtm

#314 Minor fixes around our k8s resources
  deploy/namespace.yaml
  deploy/operator.yaml
  deploy/service_account.yaml
  docs/development/deploying.md
  hack/crd.sh
Labels: approved, lgtm, ok-to-test

#313 BuildRun reconciles enhancement
  go.sum
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
  pkg/controller/buildrun/runtime_image_test.go
  test/catalog.go
Labels: approved, lgtm, ok-to-test

#321 Fix for issue #320
  pkg/controller/buildrun/buildrun_controller.go
Labels: approved, lgtm

#316 Stop working on the buildrun if build.registered=false
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  test/catalog.go
Labels: lgtm, ok-to-test
