Repository shipwright-io/build, pull requests merged in 2020-02, with the labels that each got.

#31 Add commonly used variables
  Makefile
Labels: size/S

#32 Add OWNERS file. This is required for Prow Tide
  OWNERS
Labels: do-not-merge/invalid-owners-file, size/S

#33 Fix broken link for buildpack build startegy cr
  README.md
Labels: approved, lgtm, size/XS

#34 Enable zap logr
  Makefile
Labels: approved, lgtm, size/XS
