Repository shipwright-io/build, pull requests merged in 2020-11, with the labels that each got.

#459 Bring ruby test sample back
  test/data/build_buildpacks-v3_ruby_cr.yaml
  test/data/buildrun_buildpacks-v3_ruby_cr.yaml
  test/e2e/e2e_test.go
Labels: approved, lgtm, ok-to-test

#461 Fix go module files
  go.mod
  go.sum
Labels: approved

#456 Refactor metrics observe calls to report metrics as soon as possible
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  pkg/metrics/metrics_test.go
  test/catalog.go
Labels: approved, lgtm

#460 Handle non-existing annotation
  pkg/controller/build/build_controller.go
  test/integration/build_to_buildruns_test.go
  test/integration/utils/builds.go
Labels: approved, lgtm

#465 Add build strategy labels to task run
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/buildstrategy.go
  pkg/apis/build/v1alpha1/buildstrategy_types.go
  pkg/apis/build/v1alpha1/clusterbuildstrategy_types.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
Labels: approved, lgtm

#470 tests: Do not error if ServiceAccount exists
  test/integration/utils/service_accounts.go
Labels: approved, lgtm

#471 tests: Allow the pipeline SA to be used if it is pre-existing
  test/integration/buildruns_to_sa_test.go
Labels: approved, lgtm

#473 Fixes for CRDs and fakes generator
  deploy/crds/build.dev_buildstrategies_crd.yaml
  deploy/crds/build.dev_clusterbuildstrategies_crd.yaml
  hack/generate-fakes.sh
Labels: approved, lgtm

#467 Add buildrunname label for custom metric
  docs/metrics.md
  pkg/controller/buildrun/buildrun_controller.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: approved, lgtm

#480 tests: Get BuildRun before parent Build is deleted
  test/integration/build_to_buildruns_test.go
Labels: approved, lgtm

#479 Try to fix Travis timeout during e2e tests
  Makefile
  test/e2e/validators.go
Labels: approved, lgtm

#419 [EP] Remote Artifacts
  docs/proposals/remote-artifacts.md
Labels: approved, kind/feature, lgtm

#485 Increase integration test timeouts
  test/integration/utils/environment.go
Labels: approved, lgtm

#488 Partial fix for issue 486
  test/data/build_buildpacks-v3_golang_cr.yaml
  test/data/build_buildpacks-v3_java_cr.yaml
  test/data/build_buildpacks-v3_php_cr.yaml
  test/data/build_buildpacks-v3_ruby_cr.yaml
Labels: approved, lgtm

#475 Add conditions pkg to support Build CRDs to operate on Conditions
  deploy/crds/build.dev_buildruns_crd.yaml
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/conditions/conditions.go
  pkg/conditions/conditions_suite_test.go
  pkg/conditions/conditions_test.go
  pkg/conditions/conditions_types.go
  test/catalog.go
Labels: approved, lgtm

#484 Enhance GetTRTillDesiredReason func
  test/integration/buildruns_to_taskruns_test.go
  test/integration/utils/taskruns.go
Labels: approved, lgtm

#490 Update Kaniko builder image to v1.3.0
  docs/buildstrategies.md
  pkg/config/config.go
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
Labels: approved, lgtm

#491 Use single step for all four Buildpacks lifecycle phases
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
Labels: approved, lgtm
