Repository shipwright-io/build, pull requests merged in 2020-06, with the labels that each got.

#220 Improve error handling in buildrun controllor
  pkg/controller/buildrun/buildrun_controller.go
Labels: Release 0.1.x, approved, lgtm, ok-to-test

#226 Use kaniko to build s2i's Dockerfile
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
Labels: approved, lgtm, ok-to-test

#233 Add image tag definition in buildrun spec
  docs/buildrun.md
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
Labels: Release 0.1.x, approved, lgtm, ok-to-test

#242 Handle retryable errors in from Client.Get
  test/e2e/validators.go
Labels: Release 0.1.x, approved, lgtm

#246 Enhance buildRun doc
  docs/buildrun.md
Labels: approved, lgtm, ok-to-test

#245 Change kaniko BuildStrategy from latest image to v0.19.0
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
Labels: Release 0.1.x, approved, lgtm, ok-to-test

#240 Change controller HA to leader-for-lease mode
  cmd/manager/main.go
Labels: approved, lgtm, ok-to-test

#237 Print the log of failed buildRun pod for debugging
  test/e2e/e2e_test.go
  test/e2e/samples.go
Labels: Release 0.1.x, approved, lgtm, ok-to-test

#251 Remove inactive users
  OWNERS
Labels: approved, lgtm

#252 Enhancement Proposal Process
  docs/proposals/README.md
  docs/proposals/guidelines/proposal-template.md
Labels: approved, lgtm, ok-to-test

#257 remove ruby e2e test
  test/e2e/e2e_test.go
Labels: Release 0.1.x, approved, lgtm, ok-to-test

#255 Inline BuildStrategy CRDs with ClusterBuildStrategy
  deploy/crds/build.dev_buildstrategies_crd.yaml
  pkg/apis/build/v1alpha1/buildstrategy_types.go
Labels: approved, lgtm, ok-to-test

#244 Add liveness and readness probes on the operator
  deploy/operator.yaml
Labels: Release 0.1.x, approved, lgtm, ok-to-test

#253 Add missing changes in the generated buildRun CRD
  deploy/crds/build.dev_buildruns_crd.yaml
Labels: Release 0.1.x, approved, lgtm, ok-to-test

#259 Support Ginkgo flakeAttempts flag
  HACK.md
  Makefile
  test/e2e/e2e_test.go
  test/e2e/samples.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
Labels: Release 0.1.x, approved, lgtm

#248 Improve logging and add proper go contexts
  cmd/manager/main.go
  pkg/config/config.go
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  pkg/controller/buildstrategy/buildstrategy_controller.go
  pkg/controller/buildstrategy/buildstrategy_controller_test.go
  pkg/controller/clusterbuildstrategy/clusterbuildstrategy_controller.go
  pkg/controller/clusterbuildstrategy/clusterbuildstrategy_controller_test.go
  pkg/controller/controller.go
  pkg/ctxlog/context.go
  pkg/ctxlog/log.go
Labels: Release 0.1.x, approved, lgtm, ok-to-test

#261 Allow fast fail when a travis job failed
  .travis.yml
Labels: approved, lgtm, ok-to-test

#258 Reuse generated service account
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  pkg/controller/buildrun/credentials.go
  pkg/controller/buildrun/credentials_test.go
  test/catalog.go
Labels: Release 0.1.x, approved, lgtm

#267 Upgrade to latest Kaniko version with workaround for AWS client delay
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
Labels: Release 0.1.x, approved, lgtm

#265 Delete generated service account on end of the build run
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  test/e2e/e2e_test.go
  test/e2e/validators.go
Labels: Release 0.1.x, approved, lgtm

#268 Fix the issue of args and command for probes
  deploy/operator.yaml
Labels: approved, lgtm, ok-to-test

#236 Fix Readme to mention primary CRDs
  README.md
Labels: approved, lgtm

#276 Fix readiness/liveness probe when HA is enable
  cmd/manager/main.go
  deploy/operator.yaml
Labels: approved, lgtm, ok-to-test

#275 Remove random test identifier suffix from image tag
  test/e2e/samples.go
Labels: approved, lgtm

#272 Retry net/http error in e2e tests
  test/e2e/validators.go
Labels: Release 0.1.x, approved, lgtm

#157 hard code buider image for buildpack and change default builder image
  pkg/controller/buildrun/generate_taskrun.go
  samples/build/build_buildpacks-v3-heroku_cr.yaml
  samples/build/build_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/build/build_buildpacks-v3_cr.yaml
  samples/build/build_buildpacks-v3_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
  test/data/build_buildpacks-v3-heroku_cr_private_github.yaml
  test/data/build_buildpacks-v3_cr_private_github.yaml
  test/data/build_buildpacks-v3_golang_cr.yaml
  test/data/build_buildpacks-v3_java_cr.yaml
  test/data/build_buildpacks-v3_php_cr.yaml
  test/data/build_buildpacks-v3_ruby_cr.yaml
Labels: approved, lgtm, ok-to-test

#277 Update documents because hard code builder image for buildpack
  docs/build.md
  docs/buildstrategies.md
Labels: approved, lgtm, ok-to-test

#278 Correct documentation
  docs/build.md
  docs/buildstrategies.md
Labels: Release 0.1.x, approved, lgtm

#279 Update vendor with ready pkg
  vendor/github.com/operator-framework/operator-sdk/pkg/ready/ready.go
  vendor/modules.txt
Labels: approved, lgtm

#281 This is aiming to help to mitigate performance issues in travis
  samples/build/build_buildpacks-v3-heroku_cr.yaml
  samples/build/build_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/build/build_buildpacks-v3_cr.yaml
  samples/build/build_buildpacks-v3_namespaced_cr.yaml
  test/data/build_buildpacks-v3-heroku_cr_private_github.yaml
  test/data/build_buildpacks-v3_cr_private_github.yaml
  test/data/build_buildpacks-v3_golang_cr.yaml
  test/data/build_buildpacks-v3_java_cr.yaml
  test/data/build_buildpacks-v3_php_cr.yaml
  test/data/build_buildpacks-v3_ruby_cr.yaml
Labels: approved, lgtm, ok-to-test

#273 Adding some enhancements on the logging we define.
  pkg/controller/build/build_controller.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/credentials.go
  pkg/controller/buildrun/credentials_test.go
  pkg/controller/buildstrategy/buildstrategy_controller.go
  pkg/controller/clusterbuildstrategy/clusterbuildstrategy_controller.go
  pkg/ctxlog/context.go
  pkg/ctxlog/log.go
Labels: Release 0.1.x, approved, lgtm
