Repository shipwright-io/build, pull requests merged in 2020-05, with the labels that each got.

#166 Define k8s node version
  hack/install-kind.sh
Labels: approved, lgtm

#156 BuildRun controller unit tests
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  samples/buildrun/buildrun_buildpacks-v3_namespaced_cr.yaml
  test/catalog.go
Labels: approved, lgtm, ok-to-test

#170 Add initial unit tests for buildstrategy for test coverage
  pkg/controller/buildstrategy/buildstrategy_controller.go
  pkg/controller/buildstrategy/buildstrategy_controller_test.go
  pkg/controller/buildstrategy/buildstrategy_suite_test.go
  pkg/controller/clusterbuildstrategy/clusterbuildstrategy_controller.go
  pkg/controller/clusterbuildstrategy/clusterbuildstrategy_controller_test.go
  pkg/controller/clusterbuildstrategy/clusterbuildstrategy_suite_test.go
Labels: approved, lgtm

#172 Tekton Pipelines v0.11.0
  Makefile
  hack/install-tekton.sh
Labels: approved, lgtm

#163 Rewrite e2e tests to Ginkgo and to run them in parallel
  HACK.md
  Makefile
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/e2e/ginkgo_operator-sdk.go
  test/e2e/main_test.go
  test/e2e/operator.go
  test/e2e/samples.go
  test/e2e/validators.go
Labels: approved, lgtm

#182 add +optional for omitempty json tags
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildrun_types.go
Labels: approved, lgtm, ok-to-test

#189 Fix README.md files broken links
  README.md
  docs/README.md
  docs/build.md
Labels: approved, lgtm

#179 Report proper code coverage
  .gitignore
  .travis.yml
  Makefile
Labels: approved, lgtm, ok-to-test

#191 Clean vendor obsolete packages
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#188 Add supported versions to README
  README.md
Labels: approved

#178 Migrate taskrun tests to ginkgo
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
Labels: ok-to-test

#193 Add execution time for each build in e2e tests
  test/e2e/validators.go
Labels: approved, lgtm

#158 Add timeout setting to build and buildrun
  deploy/crds/build.dev_buildruns_crd.yaml
  deploy/crds/build.dev_builds_crd.yaml
  docs/build.md
  docs/buildrun.md
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/controller/buildrun/generate_taskrun.go
  pkg/controller/buildrun/generate_taskrun_test.go
  test/data/build_timeout.yaml
  test/data/buildrun_timeout.yaml
  test/e2e/e2e_test.go
  test/e2e/validators.go
Labels: approved, lgtm

#187 Add --timestamps argument to build-logs
  hack/build-logs.sh
Labels: approved, lgtm, ok-to-test

#199 Updates Makefile to fix make local target
  Makefile
Labels: approved, lgtm

#201 Improve documentation related to timeout
  docs/build.md
  docs/buildrun.md
Labels: approved, lgtm

#204 Add BuildSpec in BuildRun status
  deploy/crds/build.dev_buildruns_crd.yaml
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  test/catalog.go
  test/e2e/validators.go
Labels: approved, lgtm

#207 Check buildRun.Status.BuildSpec at the correct places
  test/e2e/validators.go
Labels: approved, lgtm

#209 update go.mod
  go.mod
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#197 Make e2e tests configurable
  HACK.md
  Makefile
  test/e2e/e2e_suite_test.go
  test/e2e/ginkgo_operator-sdk.go
  test/e2e/validators.go
Labels: approved, lgtm

#215 Docs improvement
  README.md
  docs/buildstrategies.md
Labels: approved, lgtm, ok-to-test

#214 Document BuildRun snapshot feature
  docs/buildrun.md
Labels: approved, lgtm, ok-to-test

#212 Support contextDir for Buildpack strategies
  docs/build.md
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
  test/data/build_buildpacks-v3_golang_cr.yaml
  test/data/build_buildpacks-v3_java_cr.yaml
  test/data/build_buildpacks-v3_php_cr.yaml
  test/data/build_buildpacks-v3_ruby_cr.yaml
  test/data/buildrun_buildpacks-v3_golang_cr.yaml
  test/data/buildrun_buildpacks-v3_java_cr.yaml
  test/data/buildrun_buildpacks-v3_php_cr.yaml
  test/data/buildrun_buildpacks-v3_ruby_cr.yaml
  test/e2e/e2e_test.go
Labels: approved, lgtm, ok-to-test

#218 Propose decision making framework for BuildRun API changes
  docs/proposals/build-execution-using-build-run.md
Labels: approved, lgtm

#231 BUG: Fix the errors with heroku
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
Labels: approved, lgtm, ok-to-test

#219 Add BuildRun deletion when delete the Build
  Makefile
  docs/build.md
  go.mod
  pkg/apis/build/v1alpha1/build_types.go
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  samples/build/build_buildpacks-v3_cr.yaml
  samples/build/build_kaniko_cr.yaml
  test/catalog.go
  test/data/build_kaniko_cr_advanced_dockerfile.yaml
  test/e2e/e2e_test.go
  test/e2e/validators.go
Labels: approved, lgtm

#216 Initial goals of the BuildStrategy API
  docs/proposals/buildstrategy.md
Labels: approved, lgtm
