Repository shipwright-io/build, pull requests merged in 2021-03, with the labels that each got.

#630 Add missing rename for new ns syntax
  .github/workflows/ci.yml
  samples/build/build_ko_cr.yaml
Labels: approved, lgtm, release-note-none

#628 Add more people to reviewers
  OWNERS
Labels: approved, lgtm, release-note-none

#623 Allow to configure MaxConcurrentReconciles for our controllers
  docs/configuration.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/reconciler/build/controller.go
  pkg/reconciler/buildrun/controller.go
  pkg/reconciler/buildstrategy/controller.go
  pkg/reconciler/clusterbuildstrategy/controller.go
Labels: approved, kind/feature, lgtm, release-note

#634 Modify default branch behaviour for git repos
  docs/build.md
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
Labels: approved, lgtm, release-note

#626 Take 2: Publish nightly release assets
  .github/workflows/nightly.yaml
Labels: approved, kind/feature, lgtm, release-note-none

#637 Enhance CI e2e test on logs retrieval
  .github/workflows/ci.yml
Labels: approved, kind/bug, lgtm, release-note-none

#639 Release jobs - only run on shipwright-io/build
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
Labels: approved, kind/bug, lgtm, release-note

#629 Add make target for generating crds through controller-gen
  DEVELOPMENT.md
  Makefile
  hack/install-controller-gen.sh
Labels: approved, lgtm, release-note

#646 Remove last reference to the operator-sdk module
  cmd/manager/main.go
  go.mod
  go.sum
  vendor/github.com/operator-framework/operator-sdk/LICENSE
  vendor/github.com/operator-framework/operator-sdk/version/version.go
  vendor/modules.txt
Labels: approved, kind/cleanup, lgtm, release-note

#643 Fix CRD file naming convention
  deploy/crds/shipwright.io_buildruns_crd.yaml
  deploy/crds/shipwright.io_builds_crd.yaml
  deploy/crds/shipwright.io_buildstrategies_crd.yaml
  deploy/crds/shipwright.io_clusterbuildstrategies_crd.yaml
Labels: approved, kind/enhancement, lgtm, release-note-none

#640 Remove Travis CI
  .travis.yml
  Makefile
  README.md
  docs/development/testing.md
  hack/install-kubectl.sh
  hack/install-operator-sdk.sh
Labels: approved, kind/cleanup, lgtm, release-note-none

#648 Correct the link of controller.yaml in configuration.md
  docs/configuration.md
Labels: approved, kind/documentation, lgtm, release-note

#645 Change GitHub Action name to be more readable
  .github/workflows/ci.yml
Labels: approved, kind/feature, lgtm, release-note-none

#647 Ensure we dont mount generated serviceAccount token secret in pods
  pkg/reconciler/buildrun/resources/service_accounts.go
Labels: approved, kind/cleanup, lgtm, release-note-none

#635 Refactor git samples
  docs/build.md
  docs/buildstrategies.md
  pkg/reconciler/build/build_test.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  samples/build/build_buildah_cr.yaml
  samples/build/build_buildpacks-v3-heroku_cr.yaml
  samples/build/build_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/build/build_buildpacks-v3_cr.yaml
  samples/build/build_buildpacks-v3_namespaced_cr.yaml
  samples/build/build_kaniko_cr.yaml
  samples/build/build_source-to-image_cr.yaml
  test/build_samples.go
  test/catalog.go
  test/data/build_buildah_cr_custom_context+dockerfile.yaml
  test/data/build_buildpacks-v3_golang_cr.yaml
  test/data/build_buildpacks-v3_java_cr.yaml
  test/data/build_buildpacks-v3_nodejs_runtime-image_cr.yaml
  test/data/build_buildpacks-v3_php_cr.yaml
  test/data/build_buildpacks-v3_ruby_cr.yaml
  test/data/build_kaniko_cr_advanced_dockerfile.yaml
  test/data/build_kaniko_cr_custom_context+dockerfile.yaml
  test/data/build_timeout.yaml
  test/integration/build_to_buildruns_test.go
  test/integration/build_to_git_test.go
Labels: approved, kind/cleanup, lgtm, release-note

#649 Make Burst and QPS of the Kube API client configurable
  docs/configuration.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controller/controller.go
Labels: approved, kind/feature, lgtm, release-note

#654 Add KILL capability for Kaniko executor to allow it to kill non-root processes
  docs/buildstrategies.md
  pkg/reconciler/buildrun/resources/runtime_image.go
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/clusterbuildstrategy_samples.go
Labels: approved, lgtm, release-note

#631 Refine the other operator related names
  Makefile
  build/Dockerfile
  build/bin/entrypoint
  cmd/manager/main.go
  docs/buildstrategies.md
  docs/proposals/dedicated-shipwright-operator.md
  hack/release.sh
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/reconciler/buildrun/resources/runtime_image.go
  test/integration/integration_suite_test.go
  test/utils/controllers.go
  test/utils/environment.go
  version/version.go
Labels: approved, kind/cleanup, lgtm, release-note

#661 Fix CI nightly/release yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
Labels: approved, kind/bug, lgtm, release-note-none

#672 Git validation is disabled by default
  docs/build.md
  pkg/reconciler/build/build_test.go
  pkg/validate/sourceurl.go
  test/build_samples.go
  test/integration/build_to_git_test.go
Labels: approved, lgtm, release-note

#670 Re-generate the crds by using line breaking
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  deploy/crds/shipwright.io_buildstrategies.yaml
  deploy/crds/shipwright.io_clusterbuildstrategies.yaml
Labels: approved, kind/cleanup, lgtm, release-note-none

#676 Update generated CRDs
  .github/workflows/ci.yml
  README.md
  deploy/crds/shipwright.io_buildstrategies.yaml
  deploy/crds/shipwright.io_clusterbuildstrategies.yaml
  hack/install-kind.sh
Labels: approved, lgtm, release-note-none

#674 Deprecate .status.succeeded and .status.reason
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/reconciler/buildrun/buildrun.go
Labels: approved, kind/api-change, kind/cleanup, lgtm, release-note

#686 Rename `SpecRuntimeSecretRefNotFound` -> `SpecBuilderSecretRefNotFound`
  docs/build.md
  pkg/apis/build/v1alpha1/build_types.go
  pkg/reconciler/build/build_test.go
  pkg/validate/secrets.go
  test/integration/build_to_secrets_test.go
Labels: approved, kind/cleanup, lgtm, release-note

#683 Remove unused fields from GitSource
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  pkg/apis/build/v1alpha1/gitsource.go
Labels: approved, kind/api-change, kind/cleanup, lgtm, release-note

#641 Enhance BuildRun reconciles failure scenarios
  docs/buildrun.md
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/reconciler/buildrun/controller.go
  pkg/reconciler/buildrun/resources/build.go
  pkg/reconciler/buildrun/resources/build_test.go
  pkg/reconciler/buildrun/resources/conditions.go
  pkg/reconciler/buildrun/resources/errors.go
  pkg/reconciler/buildrun/resources/errors_test.go
  pkg/reconciler/buildrun/resources/service_accounts.go
  pkg/reconciler/buildrun/resources/service_accounts_test.go
  pkg/reconciler/buildrun/resources/strategies.go
  test/build_samples.go
  test/catalog.go
  test/integration/build_to_buildruns_test.go
  test/integration/buildruns_to_sa_test.go
Labels: approved, kind/feature, lgtm, release-note

#687 Unify Go struct field names with YAML/JSON field names
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/buildstrategy.go
  pkg/apis/build/v1alpha1/gitsource.go
  pkg/apis/build/v1alpha1/source.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/build/v1alpha1/zz_generated.openapi.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
  pkg/reconciler/build/controller.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/resources/credentials.go
  pkg/reconciler/buildrun/resources/credentials_test.go
  pkg/reconciler/buildrun/resources/runtime_image.go
  pkg/reconciler/buildrun/resources/runtime_image_test.go
  pkg/reconciler/buildrun/resources/strategies.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  pkg/validate/secrets.go
  pkg/validate/sourceurl.go
  pkg/validate/strategies.go
  pkg/validate/validate.go
  test/catalog.go
  test/e2e/common_test.go
  test/integration/build_to_git_test.go
  test/integration/build_to_secrets_test.go
  test/integration/buildruns_to_sa_test.go
Labels: approved, kind/cleanup, lgtm, release-note

#690 Tag nightly releases to avoid quay GC
  .github/workflows/nightly.yaml
Labels: approved, kind/bug, lgtm, release-note

#669 Readme reorganize
  .docs/shipwright-logo-lightbg-512.png
  README.md
  docs/buildstrategies.md
  docs/tutorials/README.md
  docs/tutorials/building_with_buildpacks.md
  docs/tutorials/building_with_kaniko.md
Labels: approved, kind/documentation, lgtm, release-note

#685 Add EP for synchronous webhook validation
  docs/proposals/webhook-validation.md
Labels: approved, kind/feature, lgtm, release-note-none

#704 Change to use build/buildrun yaml for nodejs sample
  test/e2e/e2e_test.go
  test/e2e/validators_test.go
Labels: do-not-merge/release-note-label-needed

#695 Update KinD version to the same v0.10.0
  hack/install-kind.sh
Labels: approved, kind/cleanup, lgtm, release-note-none

#703 Minor fixes to the readme
  README.md
Labels: approved, lgtm
