Repository shipwright-io/build, pull requests merged in 2021-12, with the labels that each got.

#953 Fix incorrect flag name
  pkg/reconciler/buildrun/resources/sources/git.go
Labels: kind/bug, lgtm, approved, release-note

#713 fix: avoid AWS-related error in kaniko container
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
Labels: lgtm, approved, release-note

#957 Remove compatability code to remove service account with -sa suffix
  docs/buildrun.md
  pkg/reconciler/buildrun/resources/service_accounts.go
  pkg/reconciler/buildrun/resources/service_accounts_test.go
Labels: lgtm, approved, kind/cleanup, release-note

#956 Update Trivy to 0.21.2
  samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
Labels: lgtm, approved, kind/dependency-change, release-note

#938 Sign released images
  .github/workflows/release.yaml
Labels: kind/feature, lgtm, approved, release-note

#960 Fail in case there is an error event
  .github/workflows/ci.yml
  test/integration/buildruns_to_taskruns_test.go
Labels: lgtm, approved, kind/failing-test, release-note-none

#962 Grant release workflow permission to create PRs
  .github/workflows/release.yaml
Labels: lgtm, approved, kind/cleanup, release-note-none

#964 Use golangci-lint in CI
  .github/workflows/verify.yaml
  .golangci.yaml
  Makefile
Labels: lgtm, approved, kind/cleanup, release-note-none
