Repository shipwright-io/build, pull requests merged in 2021-10, with the labels that each got.

#882 Fix the gosec finding TLS MinVersion too low
  cmd/mutate-image/main.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#883 Publish latest tag during nightly release / publish sample strategies
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  hack/release.sh
Labels: kind/feature, lgtm, approved, release-note

#871 Surface Step Results in BuildRun Status
  cmd/bundle/main.go
  cmd/bundle/main_test.go
  cmd/git/main.go
  cmd/git/main_test.go
  cmd/mutate-image/main.go
  cmd/mutate-image/main_test.go
  deploy/crds/shipwright.io_buildruns.yaml
  docs/buildrun.md
  docs/buildstrategies.md
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/bundle/bundle.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/resources/mutate.go
  pkg/reconciler/buildrun/resources/results.go
  pkg/reconciler/buildrun/resources/results_test.go
  pkg/reconciler/buildrun/resources/sources.go
  pkg/reconciler/buildrun/resources/sources/bundle.go
  pkg/reconciler/buildrun/resources/sources/git.go
  pkg/reconciler/buildrun/resources/sources/git_test.go
  pkg/reconciler/buildrun/resources/sources/utils.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  test/e2e/e2e_bundle_test.go
  test/e2e/e2e_image_mutate_test.go
  test/e2e/e2e_test.go
  test/e2e/validators_test.go
Labels: lgtm, approved, kind/api-change, release-note

#884 Only run the TaskRun checks if Tekton objects can be accessed
  test/e2e/validators_test.go
Labels: kind/bug, lgtm, approved, release-note-none

#879 Fix kind installation
  hack/install-kind.sh
Labels: lgtm, approved, kind/cleanup, release-note-none

#887 Use `--no-tags` only when available
  cmd/git/main.go
Labels: kind/bug, lgtm, approved, release-note-none

#888 Remove stale `go.sum` `k8s.io/kubernetes` entry
  go.sum
Labels: lgtm, approved, kind/cleanup, release-note-none

#817 SHIP-0004: Build Environment Variables
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  docs/build.md
  docs/buildrun.md
  go.sum
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/bundle_suite_test.go
  pkg/env/env.go
  pkg/env/env_test.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  pkg/validate/envvars.go
  pkg/validate/envvars_test.go
  pkg/validate/validate.go
  test/build_samples.go
  test/buildrun_samples.go
  test/buildstrategy_samples.go
  test/bundle/README.md
Labels: kind/feature, lgtm, approved, kind/api-change, release-note

#885 Remove -sa suffix from generated service account
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/reconciler/buildrun/resources/service_accounts.go
  pkg/reconciler/buildrun/resources/service_accounts_test.go
  test/e2e/validators_test.go
  test/integration/buildruns_to_sa_test.go
Labels: kind/bug, lgtm, approved, release-note

#890 Add check to verify `--depth` can be used
  cmd/git/main.go
Labels: kind/bug, lgtm, approved, release-note-none

#899 Fix documentation links
  HACK.md
  README.md
  docs/buildrun.md
  docs/buildstrategies.md
  docs/development/testing.md
  docs/metrics.md
  docs/tutorials/README.md
  docs/tutorials/building_with_buildkit.md
  docs/tutorials/building_with_buildpacks.md
  docs/tutorials/building_with_kaniko.md
Labels: lgtm, approved, kind/documentation, release-note-none

#906 Extend the Buildpack strategy to work with the environment variables
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
  test/data/build_buildpacks-v3_golang_cr_env.yaml
  test/e2e/e2e_test.go
Labels: kind/feature, lgtm, approved, release-note

#909 Update Kaniko to v1.7.0
  docs/buildstrategies.md
  samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/clusterbuildstrategy_samples.go
Labels: lgtm, approved, kind/dependency-change, release-note
