Repository shipwright-io/build, pull requests merged in 2021-04, with the labels that each got.

#708 Change to use git protocol for git url
  test/data/build_buildpacks-v3_private_github_cr.yaml
Labels: approved, do-not-merge/release-note-label-needed, lgtm

#710 Fix nil-pointer dereference of BuildSpec Strategy
  pkg/apis/build/v1alpha1/build_types.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/buildrun_test.go
Labels: approved, kind/bug, lgtm, release-note

#715 Update Kaniko to v1.5.2
  docs/build.md
  docs/buildstrategies.md
  docs/configuration.md
  pkg/config/config.go
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/clusterbuildstrategy_samples.go
Labels: approved, kind/dependency-change, lgtm, release-note

#714 Add missing log labels
  pkg/validate/sourceurl.go
  pkg/validate/strategies.go
Labels: approved, kind/cleanup, lgtm, release-note-none

#712 validate PR release-note text, skip entries with invalid format; various sh/bash differences between fedora and ubuntu; add sorting based on kind labels
  .github/draft_release_notes.sh
  .github/pull_request_template.md
Labels: approved, lgtm, release-note-none

#675 Add support for Buildkit
  README.md
  docs/buildstrategies.md
  docs/tutorials/README.md
  docs/tutorials/building_with_buildkit.md
  samples/build/build_buildkit_cr.yaml
  samples/buildrun/buildrun_buildkit_cr.yaml
  samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/buildstrategy/buildkit/buildstrategy_buildkit_insecure_cr.yaml
  test/data/build_buildkit_cr_insecure_registry.yaml
  test/e2e/e2e_test.go
Labels: approved, kind/feature, lgtm, release-note

#709 Add 2021 roadmap
  2021-roadmap.md
Labels: approved, kind/documentation, lgtm, release-note-none

#711 Multi-platform support
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  Makefile
  README.md
  docs/buildstrategies.md
  hack/release.sh
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
Labels: approved, kind/feature, lgtm, release-note

#720 Remove the operator-sdk settings
  HACK.md
  Makefile
  docs/development/local_development.md
  hack/README.md
  hack/install-operator-sdk.sh
  openshift-ci/Dockerfile.tools
Labels: approved, kind/cleanup, lgtm, release-note

#728 Handle nil buildSpec
  pkg/apis/build/v1alpha1/build_types.go
Labels: approved, kind/bug, lgtm, release-note

#731 Add EP: Modifying Output Image
  docs/proposals/modifying-output-image.md
Labels: approved, kind/feature, lgtm, release-note-none

#697 Add EP on Build Strategies Parametrization
  docs/proposals/parameterize-strategies.md
Labels: approved, lgtm, release-note

#727 Proposal to remove Tekton resources
  docs/proposals/removal-tekton-resources.md
Labels: approved, kind/design, lgtm, release-note-none

#738 Ensure GO_OS does not us an OS that isn´t supported
  Makefile
Labels: approved, kind/bug, lgtm, release-note-none

#739 Reflect v0.4.0 in README.md
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none

#741 Bump Tekton to v0.23.0
  Makefile
  README.md
  go.mod
  go.sum
  hack/install-tekton.sh
  vendor/github.com/Azure/go-autorest/autorest/adal/token.go
  vendor/github.com/Azure/go-autorest/autorest/adal/token_1.13.go
  vendor/github.com/Azure/go-autorest/autorest/adal/token_legacy.go
  vendor/github.com/Azure/go-autorest/autorest/authorization.go
  vendor/github.com/Azure/go-autorest/autorest/authorization_sas.go
  vendor/github.com/Azure/go-autorest/autorest/authorization_storage.go
  vendor/github.com/Azure/go-autorest/autorest/azure/async.go
  vendor/github.com/Azure/go-autorest/autorest/azure/azure.go
  vendor/github.com/Azure/go-autorest/autorest/azure/environments.go
  vendor/github.com/Azure/go-autorest/autorest/client.go
  vendor/github.com/Azure/go-autorest/autorest/error.go
  vendor/github.com/Azure/go-autorest/autorest/go.mod
  vendor/github.com/Azure/go-autorest/autorest/go.sum
  vendor/github.com/Azure/go-autorest/autorest/preparer.go
  vendor/github.com/Azure/go-autorest/autorest/sender.go
  vendor/github.com/Azure/go-autorest/autorest/utility.go
  vendor/github.com/Azure/go-autorest/autorest/utility_1.13.go
  vendor/github.com/Azure/go-autorest/autorest/utility_legacy.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/images.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/conversion_error.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipelinerun_conversion.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/storage_resource.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/task_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resource/v1alpha1/pipeline_resource_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resource/v1alpha1/pipelineresource_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/contexts/contexts.go
  vendor/modules.txt
Labels: approved, kind/dependency-change, lgtm, release-note

#733 Remove pkg/controller/ready
  cmd/manager/main.go
  deploy/500-controller.yaml
  pkg/controller/controller.go
  pkg/controller/ready/ready.go
  pkg/controller/ready/ready_suite_test.go
  pkg/controller/ready/ready_test.go
Labels: approved, kind/cleanup, lgtm, release-note

#737 Provide well-documented parameters for source and image for the build strategy author
  docs/buildstrategies.md
  docs/proposals/removal-tekton-resources.md
  pkg/reconciler/buildrun/resources/remote_artifacts.go
  pkg/reconciler/buildrun/resources/runtime_image.go
  pkg/reconciler/buildrun/resources/runtime_image_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
  samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/buildstrategy/buildkit/buildstrategy_buildkit_insecure_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/buildstrategy_samples.go
  test/clusterbuildstrategy_samples.go
Labels: approved, kind/feature, lgtm, release-note-action-required

#745 Update Kaniko to 1.6.0, update ko to 0.8.2
  .github/workflows/ci.yml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  docs/build.md
  docs/buildstrategies.md
  docs/configuration.md
  pkg/config/config.go
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/clusterbuildstrategy_samples.go
Labels: approved, kind/dependency-change, lgtm, release-note

#743 Add make target to run unit tests with ginkgo
  Makefile
Labels: approved, kind/cleanup, lgtm, release-note-none

#746 Fix typo in reason, fix links
  docs/build.md
Labels: approved, kind/bug, lgtm, release-note

#749 Pin buildah version
  docs/buildstrategies.md
  pkg/reconciler/buildrun/resources/taskrun_test.go
  samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
  test/buildstrategy_samples.go
  test/clusterbuildstrategy_samples.go
Labels: approved, kind/dependency-change, lgtm, release-note

#740 Removing PR template block on notes verification
  .github/pull_request_template.md
Labels: approved, kind/cleanup, lgtm, release-note-none

#747 Use imjasonh/setup-ko GitHub Action
  .github/workflows/ci.yml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
Labels: approved, kind/cleanup, lgtm, release-note-none
