Repository shipwright-io/build, pull requests merged in 2021-09, with the labels that each got.

#843 Add shipwright sample pre-req image mirroring
  .github/workflows/mirror-images.yaml
Labels: lgtm, approved, kind/cleanup, release-note-none

#859 Fix output image credentials for bundle E2E
  test/e2e/common_suite_test.go
  test/e2e/e2e_bundle_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#858 Set user-friendly BuildRun status when Pod gets evicted
  docs/buildrun.md
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/reconciler/buildrun/resources/conditions.go
  pkg/reconciler/buildrun/resources/conditions_test.go
Labels: kind/feature, lgtm, approved, release-note

#860 Ensure Note msg doesn't belong to the conditions Table
  docs/buildrun.md
Labels: lgtm, approved, kind/documentation, release-note-none

#864 Use Go `1.16` in GitHub Actions
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/verify.yaml
Labels: kind/bug, lgtm, approved, release-note-none

#861 Update docs with regards to local source feature
  HACK.md
  docs/proposals/enable-local-source-code-support.md
Labels: lgtm, approved, kind/cleanup, release-note-none

#862 Update docs/proposals to reflect community SHIPs
  docs/proposals/README.md
  docs/proposals/build-execution-using-build-run.md
  docs/proposals/buildstrategy-annotation-propagation.md
  docs/proposals/buildstrategy-steps-resources.md
  docs/proposals/buildstrategy.md
  docs/proposals/cli.md
  docs/proposals/dedicated-shipwright-operator.md
  docs/proposals/enable-local-source-code-support.md
  docs/proposals/local-registry-image-specs.md
  docs/proposals/modifying-output-image.md
  docs/proposals/parameterize-strategies.md
  docs/proposals/remote-artifacts.md
  docs/proposals/removal-tekton-resources.md
  docs/proposals/runtime-image.md
  docs/proposals/shipwright-website.md
  docs/proposals/webhook-validation.md
Labels: lgtm, approved, kind/documentation, release-note-none

#863 Update mirror action config
  .github/workflows/mirror-images.yaml
Labels: kind/bug, lgtm, approved, release-note-none

#865 Mitigate bundle E2E test build create issue
  test/e2e/common_suite_test.go
Labels: kind/bug, lgtm, approved, release-note-none

#868 [ci] Remove unnecessary matrix values
  .github/workflows/ci.yml
Labels: lgtm, approved, kind/cleanup, release-note-none

#869 Remove Kaniko image configuration of runtime image feature
  docs/configuration.md
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#872 Fixing oc policy command in HACK.md
  .gitignore
  HACK.md
Labels: lgtm, approved, kind/documentation, release-note-none

#870 Add `verify-generate.sh` script
  .github/workflows/verify.yaml
  Makefile
  hack/generate-fakes.sh
  hack/verify-generate.sh
Labels: lgtm, approved, kind/cleanup, release-note-none

#875 Fix should mutate an image e2e test fail
  docs/configuration.md
  pkg/config/config.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  test/integration/build_to_taskruns_test.go
Labels: kind/bug, lgtm, approved, release-note-none

#878 Add help flag to supporting binaries
  cmd/bundle/main.go
  cmd/bundle/main_test.go
  cmd/git/main.go
  cmd/git/main_test.go
  cmd/mutate-image/main.go
  cmd/mutate-image/main_test.go
Labels: kind/feature, lgtm, approved, release-note-none

#880 Remove incorrect statement about contextDir limitation
  docs/build.md
Labels: lgtm, approved, kind/documentation, release-note
