Repository shipwright-io/build, pull requests merged in 2021-06, with the labels that each got.

#789 Add image digest result to remaining sample build strategies
  docs/proposals/removal-tekton-resources.md
  samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
  samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/buildstrategy/buildkit/buildstrategy_buildkit_insecure_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
Labels: approved, kind/feature, lgtm, release-note-none

#793 Check for Tekton installed before running the manager
  cmd/shipwright-build-controller/main.go
  docs/configuration.md
  pkg/config/config.go
Labels: approved, kind/bug, lgtm, release-note

#794 Removing preceding '$' from code blocks
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none

#786 Re-run make generate and generate-crds
  .gitignore
  2021-roadmap.md
  cmd/git/README.md
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  deploy/crds/shipwright.io_buildstrategies.yaml
  deploy/crds/shipwright.io_clusterbuildstrategies.yaml
  docs/tutorials/README.md
  docs/tutorials/building_with_buildkit.md
  docs/tutorials/building_with_buildpacks.md
  docs/tutorials/building_with_kaniko.md
  hack/install-controller-gen.sh
  images/git/Dockerfile
Labels: approved, kind/cleanup, lgtm, release-note-none

#796 Add deprecation warnings for .spec.runtime
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  docs/build.md
  pkg/apis/build/v1alpha1/build_types.go
  pkg/reconciler/buildrun/resources/runtime_image.go
  pkg/reconciler/buildrun/resources/runtime_image_test.go
  pkg/validate/runtime.go
Labels: approved, kind/cleanup, lgtm, release-note

#797 Rename basic static checks to "Verify"
  .github/workflows/verify.yaml
Labels: approved, kind/cleanup, lgtm, release-note-none

#799 Fix typo in release.yaml
  .github/workflows/release.yaml
Labels: approved, kind/cleanup, lgtm, release-note-none

#800 Fix another typo in release.yaml
  .github/workflows/release.yaml
Labels: approved, kind/cleanup, lgtm, release-note-none

#802 Update documentation
  HACK.md
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none

#804 Extend CI with README updates
  .github/workflows/release.yaml
  .gitignore
Labels: approved, kind/cleanup, lgtm, release-note

#807 Fix RBAC so Shipwright Build works with the OwnerReferencesPermissionEnforcement admission controller
  .github/workflows/ci.yml
  deploy/200-role.yaml
  test/data/build_buildpacks-v3_golang_delete_cr.yaml
  test/e2e/e2e_test.go
  test/kind/config.yaml
Labels: approved, kind/bug, lgtm, release-note

#815 Tweak Git image size
  images/git/Dockerfile
Labels: approved, kind/cleanup, lgtm

#813 Improve submodule loading
  cmd/git/main.go
Labels: approved, kind/bug, lgtm, release-note

#816 Add step name to message
  pkg/reconciler/buildrun/resources/conditions.go
  test/integration/buildruns_to_taskruns_test.go
Labels: approved, kind/feature, lgtm, release-note

#818 Remove Tekton annotations from Git related secrets
  docs/development/authentication.md
Labels: approved, kind/documentation, lgtm, release-note-none

#805 Bump Tekton Release to v0.25.0
  Makefile
  README.md
  go.mod
  go.sum
  hack/install-tekton.sh
  pkg/reconciler/buildrun/resources/runtime_image.go
  samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/feature_flags.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/pod/template.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/pod/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/cluster_task_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/condition_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipelinerun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/run_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/run_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/task_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/taskrun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/cluster_task_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/openapi_generated.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/swagger.json
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/task_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/task_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/version_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/when_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/when_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/workspace_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resource/v1alpha1/pipelineresource_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/validate/metadata.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/pipeline/dag/dag.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/modules.txt
Labels: approved, kind/dependency-change, lgtm, release-note

#781 Params EP Implementation
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  deploy/crds/shipwright.io_buildstrategies.yaml
  deploy/crds/shipwright.io_clusterbuildstrategies.yaml
  docs/build.md
  docs/buildrun.md
  docs/buildstrategies.md
  docs/proposals/parameterize-strategies.md
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/buildstrategy.go
  pkg/apis/build/v1alpha1/buildstrategy_types.go
  pkg/apis/build/v1alpha1/clusterbuildstrategy_types.go
  pkg/apis/build/v1alpha1/parameter.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/buildrun/resources/params.go
  pkg/reconciler/buildrun/resources/params_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  pkg/validate/strategies.go
  samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/buildstrategy/buildkit/buildstrategy_buildkit_insecure_cr.yaml
  test/build_samples.go
  test/buildrun_samples.go
  test/buildstrategy_samples.go
  test/clusterbuildstrategy_samples.go
  test/data/build_buildkit_cr_insecure_registry.yaml
  test/integration/buildstrategy_to_taskruns_test.go
Labels: approved, kind/api-change, kind/feature, lgtm, release-note
