Repository shipwright-io/build, pull requests merged in 2021-08, with the labels that each got.

#846 Update links to point to restrictions for a label value
  docs/build.md
  docs/buildrun.md
Labels: approved, kind/documentation, lgtm, release-note-none

#848 Improve Documentation for build and buildRun
  docs/build.md
  docs/buildstrategies.md
Labels: lgtm, approved, release-note

#844 Add kaniko+trivy strategy to samples
  docs/buildstrategies.md
  samples/build/build_kaniko-trivy-bad_cr.yaml
  samples/build/build_kaniko-trivy-good_cr.yaml
  samples/buildrun/buildrun_kaniko-trivy-bad_cr.yaml
  samples/buildrun/buildrun_kaniko-trivy-good_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
  test/e2e/e2e_test.go
  test/e2e/validators_test.go
Labels: lgtm, approved, release-note-none

#850 remove inactive reviewers
  OWNERS
Labels: lgtm, approved, release-note

#836 Remove runtime feature
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  docs/build.md
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/build/build.go
  pkg/reconciler/buildrun/resources/runtime_image.go
  pkg/reconciler/buildrun/resources/runtime_image_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/validate/runtime.go
  pkg/validate/validate.go
  test/data/build_buildpacks-v3_nodejs_runtime-image_cr.yaml
  test/e2e/e2e_test.go
Labels: lgtm, approved, kind/cleanup, kind/api-change, release-note

#822 Parameterize ko build strategy
  docs/buildstrategies.md
  samples/build/build_ko_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
Labels: lgtm, approved, release-note-action-required

#855 Add missing closing back-quote
  docs/buildstrategies.md
Labels: lgtm, approved, kind/documentation, release-note-none

#856 Minor fixes on spelling for mutate img binary pgk
  cmd/mutate-image/README.md
Labels: lgtm, approved, kind/documentation, release-note-none

#835 Local source code feature (using bundle images)
  .github/workflows/ci.yml
  .github/workflows/verify.yaml
  cmd/bundle/bundle_suite_test.go
  cmd/bundle/main.go
  cmd/bundle/main_test.go
  deploy/500-controller.yaml
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
  pkg/apis/build/v1alpha1/source.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/bundle.go
  pkg/bundle/bundle_suite_test.go
  pkg/bundle/bundle_test.go
  pkg/config/config.go
  pkg/reconciler/buildrun/resources/sources.go
  pkg/reconciler/buildrun/resources/sources/bundle.go
  pkg/validate/sources_test.go
  samples/build/build_ko_cr.yaml
  test/bundle/.shpignore
  test/bundle/.someToolDir/config.json
  test/bundle/README.md
  test/bundle/linktofile
  test/bundle/somefile
  test/e2e/common_suite_test.go
  test/e2e/common_test.go
  test/e2e/e2e_bundle_test.go
  test/e2e/validators_test.go
  test/integration/buildruns_to_taskruns_test.go
Labels: kind/feature, lgtm, approved, kind/api-change, release-note
