Repository shipwright-io/build, pull requests merged in 2021-05, with the labels that each got.

#750 Let buildrun override output secret
  docs/buildrun.md
  pkg/reconciler/buildrun/resources/credentials.go
  pkg/reconciler/buildrun/resources/credentials_test.go
  pkg/reconciler/buildrun/resources/service_accounts.go
Labels: approved, kind/bug, lgtm, release-note

#755 Add Jason as an approver
  OWNERS
Labels: approved, kind/design, kind/documentation, lgtm, release-note

#760 Add support for contextDir in S2I strategy
  docs/build.md
  samples/build/build_source-to-image_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
Labels: approved, kind/cleanup, kind/documentation, lgtm, release-note

#761 Enhance integration flaky test case
  test/integration/build_to_buildruns_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none

#763 Run daily base images build only in main repository
  .github/workflows/base-images.yaml
Labels: approved, kind/cleanup, lgtm, release-note-none

#766 Tag release images with release version
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
Labels: approved, kind/bug, lgtm, release-note

#764 Retry build creation if build controller did not find build strategy
  test/e2e/common_test.go
Labels: approved, kind/failing-test, lgtm, release-note-none

#762 Cleanup namespace after test case
  test/integration/integration_suite_test.go
  test/utils/environment.go
  test/utils/namespaces.go
Labels: approved, kind/failing-test, lgtm, release-note-none

#751 Introduce Git step command
  .ko.yaml
  Makefile
  cmd/git/README.md
  cmd/git/main.go
  cmd/git/main_suite_test.go
  cmd/git/main_test.go
Labels: approved, kind/feature, lgtm, release-note

#769 Ensure buildrun is not nil
  pkg/reconciler/buildrun/resources/credentials_test.go
Labels: approved, kind/failing-test, lgtm, release-note-none

#771 Add sanity check on release notes content
  .github/workflows/release-notes-linter.yaml
Labels: approved, kind/cleanup, lgtm, release-note

#772 Rebuild build object on retry
  test/e2e/common_test.go
Labels: approved, kind/failing-test, lgtm, release-note-none

#773 Skip Git LFS tests in case there is no Git LFS
  cmd/git/main.go
  cmd/git/main_test.go
Labels: approved, kind/failing-test, lgtm, release-note-none

#774 Add settings to disable user prompts
  cmd/git/main.go
Labels: approved, kind/bug, lgtm, release-note-none

#768 Reduce requested RBAC permissions
  deploy/200-role.yaml
  deploy/300-rolebinding.yaml
Labels: approved, kind/cleanup, lgtm, release-note

#775 Mitigate context deadline exceeded issue
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/validate/sourceurl.go
Labels: approved, kind/failing-test, lgtm, release-note

#767 Don't rely on actions/upload-release-asset
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
Labels: approved, kind/cleanup, lgtm, release-note-none

#671 Change to main branch in the internal flow
  .github/pull_request_template.md
  .github/workflows/ci.yml
  .github/workflows/sanity-checks.yaml
  docs/development/testing.md
Labels: approved, kind/cleanup, lgtm, release-note

#779 Update reviewers
  OWNERS
Labels: approved, kind/cleanup, lgtm, release-note-none

#778 Remove CRDs files duplication
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_buildruns_crd.yaml
  deploy/crds/shipwright.io_builds.yaml
  deploy/crds/shipwright.io_builds_crd.yaml
  deploy/crds/shipwright.io_buildstrategies.yaml
  deploy/crds/shipwright.io_buildstrategies_crd.yaml
  deploy/crds/shipwright.io_clusterbuildstrategies.yaml
  deploy/crds/shipwright.io_clusterbuildstrategies_crd.yaml
Labels: approved, kind/bug, kind/cleanup, lgtm, release-note-none

#776 Add commit SHA label to SHP image
  hack/release.sh
Labels: approved, kind/feature, lgtm, release-note

#753 Add security context to BuildKit strategy sample
  docs/buildstrategies.md
  samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/buildstrategy/buildkit/buildstrategy_buildkit_insecure_cr.yaml
Labels: approved, kind/cleanup, lgtm, release-note-none

#770 Remove usage of Tekton resources
  .github/workflows/ci.yml
  Makefile
  cmd/shipwright-build-controller/main.go
  deploy/500-controller.yaml
  docs/buildstrategies.md
  docs/configuration.md
  docs/proposals/removal-tekton-resources.md
  docs/tutorials/README.md
  hack/release.sh
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/reconciler/buildrun/resources/credentials.go
  pkg/reconciler/buildrun/resources/credentials_test.go
  pkg/reconciler/buildrun/resources/remote_artifacts.go
  pkg/reconciler/buildrun/resources/remote_artifacts_test.go
  pkg/reconciler/buildrun/resources/runtime_image.go
  pkg/reconciler/buildrun/resources/runtime_image_test.go
  pkg/reconciler/buildrun/resources/sources.go
  pkg/reconciler/buildrun/resources/sources/git.go
  pkg/reconciler/buildrun/resources/sources/git_test.go
  pkg/reconciler/buildrun/resources/sources/http.go
  pkg/reconciler/buildrun/resources/sources/http_test.go
  pkg/reconciler/buildrun/resources/sources/sources_suite_test.go
  pkg/reconciler/buildrun/resources/sources/utils.go
  pkg/reconciler/buildrun/resources/sources/utils_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  samples/build/build_ko_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/clusterbuildstrategy_samples.go
  test/integration/build_to_buildruns_test.go
  test/utils/controllers.go
  test/utils/gomega.go
Labels: approved, kind/feature, lgtm, release-note

#783 Only add secret to build for private repos
  test/e2e/common_test.go
Labels: approved, lgtm, release-note-none

#782 Update ko and tested Kubernetes version
  .github/workflows/ci.yml
  hack/install-kind.sh
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
Labels: approved, kind/dependency-change, lgtm, release-note

#717 Add EP on enabling local source code support
  docs/proposals/enable-local-source-code-support.md
Labels: approved, kind/feature, lgtm, release-note

#792 Fix Git submodule update issue with SSH creds
  cmd/git/main.go
Labels: approved, kind/bug, lgtm, release-note

#791 Map ImagePullPolicy from build strategy step to TaskRun step
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/buildstrategy/buildkit/buildstrategy_buildkit_insecure_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
Labels: approved, kind/feature, lgtm, release-note
