Repository shipwright-io/build, pull requests merged in 2021-11, with the labels that each got.

#931 Omit output during unit test
  cmd/bundle/main_test.go
  cmd/git/main_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#932 Actually mirror images using crane
  .github/workflows/mirror-images.yaml
Labels: kind/bug, lgtm, approved, release-note-none

#933 Adds branchName in buildrun results if revision is not specified
  cmd/git/main.go
  cmd/git/main_test.go
  deploy/crds/shipwright.io_buildruns.yaml
  docs/buildrun.md
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/reconciler/buildrun/resources/sources/git.go
  pkg/reconciler/buildrun/resources/sources/git_test.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  test/e2e/validators_test.go
Labels: kind/feature, lgtm, approved, kind/api-change, release-note

#903 Add CII Best Practices Badge
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none

#918 Sign nightly released images
  .github/workflows/nightly.yaml
Labels: kind/feature, lgtm, approved, release-note-none

#940 Run gosec as part of the verify action
  .github/workflows/verify.yaml
  Makefile
Labels: lgtm, approved, kind/cleanup, release-note-none

#944 Adds support for specifying image labels and annotation in buildrun
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/buildrun/resources/mutate.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  test/buildrun_samples.go
Labels: kind/feature, lgtm, approved, release-note

#928 Usage of paths-ignore in github actions to reduce time check in e2e tests
  .github/workflows/ci.yml
Labels: lgtm, approved, kind/cleanup, release-note-none

#925 Move some more quay.io references to ghcr.io
  Makefile
  docs/configuration.md
  hack/release.sh
  pkg/config/config.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#947 Update image spec to v1.0.2
  go.mod
  go.sum
  vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/modules.txt
Labels: lgtm, approved, kind/dependency-change, release-note-none

#946 Update Verify CI job to check CRD generation
  .github/workflows/verify.yaml
  DEVELOPMENT.md
  Makefile
  hack/README.md
  hack/verify-generate.sh
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#937 Introduce Git config URL rewrite option
  cmd/git/main.go
  cmd/git/main_test.go
  deploy/500-controller.yaml
  docs/configuration.md
  pkg/config/config.go
  pkg/reconciler/buildrun/resources/sources/git.go
Labels: kind/feature, lgtm, approved, release-note

#952 Fix Git URL rewrite issue for HTTPS URLs
  cmd/git/main.go
  cmd/git/main_test.go
Labels: kind/bug, lgtm, approved, release-note
