Repository shipwright-io/build, pull requests merged in 2021-07, with the labels that each got.

#828 Update reference to community meetings
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none

#829 Fix build
  .github/workflows/ci.yml
  hack/install-kind.sh
Labels: approved, kind/dependency-change, kind/failing-test, lgtm, release-note-none

#830 linting
  pkg/validate/validate.go
  test/integration/build_to_buildruns_test.go
Labels: approved, lgtm, release-note

#831 Add check for controller gen version
  hack/install-controller-gen.sh
Labels: approved, kind/cleanup, lgtm, release-note-none

#819 Add Kubectl binary download script for all Linux distributions
  hack/install-kubectl.sh
Labels: approved, lgtm, release-note-none

#833 Enable script for arm64
  hack/install-kubectl.sh
Labels: approved, kind/cleanup, lgtm, release-note-none

#809 add cancel buildrun support
  deploy/200-role.yaml
  deploy/crds/shipwright.io_buildruns.yaml
  docs/buildrun.md
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/reconciler/buildrun/controller.go
  pkg/reconciler/buildrun/resources/conditions.go
  test/catalog.go
  test/integration/buildruns_to_sa_test.go
  test/integration/buildruns_to_taskruns_test.go
  test/utils/buildruns.go
Labels: approved, kind/api-change, kind/feature, lgtm, release-note

#841 Refactor E2E test service account setup
  test/e2e/validators_test.go
Labels: approved, kind/failing-test, lgtm, release-note-none

#839 Declutter Git step log output
  cmd/git/main.go
  images/git/Dockerfile
Labels: approved, kind/cleanup, lgtm, release-note

#837 Increase log output readability
  cmd/git/main.go
  cmd/git/main_test.go
Labels: approved, kind/cleanup, lgtm, release-note

#840 Enforce label name limits in resource names
  docs/build.md
  docs/buildrun.md
  pkg/apis/build/v1alpha1/build_types.go
  pkg/reconciler/build/build.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/resources/conditions.go
  pkg/validate/buildname.go
  pkg/validate/validate.go
  test/integration/build_to_buildruns_test.go
  test/integration/buildruns_to_taskruns_test.go
Labels: approved, kind/bug, lgtm, release-note

#842 Clean-up test data directory
  test/data/build_buildpacks-v3-heroku_cr_private_github.yaml
  test/data/build_buildpacks-v3_cr_private_github.yaml
  test/data/build_source-to-image_cr_private_github.yaml
  test/data/build_timeout.yaml
Labels: approved, kind/cleanup, lgtm, release-note-none
