Repository shipwright-io/build, pull requests merged in 2021-02, with the labels that each got.

#549 Add more labels for Counter count metrics
  docs/metrics.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controller/build/build_controller.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: approved, lgtm

#556 Replace mailto links for Shipwright email lists
  README.md
Labels: approved, lgtm

#534 Update main README.md
  README.md
Labels: approved, lgtm

#536 Refactor Build Status fields
  deploy/crds/build.dev_builds_crd.yaml
  docs/build.md
  go.mod
  pkg/apis/build/v1alpha1/build_types.go
  pkg/controller/build/build_controller.go
  pkg/controller/build/build_controller_test.go
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  pkg/validate/ownerreferences.go
  pkg/validate/runtime.go
  pkg/validate/secrets.go
  pkg/validate/sourceurl.go
  pkg/validate/strategies.go
  pkg/validate/validate.go
  test/catalog.go
  test/integration/build_to_buildruns_test.go
  test/integration/build_to_git_test.go
  test/integration/build_to_secrets_test.go
  test/integration/buildruns_to_taskruns_test.go
  test/integration/utils/builds.go
  vendor/modules.txt
Labels: approved, lgtm

#564 Fix flaky unit-test spec for Build
  pkg/validate/secrets.go
Labels: approved, lgtm

#548 Fix missing BuildRun Conditions updates on errors
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
  test/buildrun_samples.go
  test/catalog.go
  test/integration/build_to_buildruns_test.go
  test/integration/buildruns_to_sa_test.go
Labels: approved, lgtm

#550 CVE-2021-3121 (skippy peanut butter)
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/modules.txt
Labels: approved, lgtm

#570 Accept ExceededNodeResources as a valid Reason in integration tests
  test/integration/build_to_buildruns_test.go
Labels: approved, lgtm, ok-to-test

#565 Add trimpath Go build flag
  Makefile
Labels: approved, lgtm

#566 Sync Go and operator SDK versions used
  .travis.yml
  Dockerfile
  HACK.md
  Makefile
  go.mod
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#571 Don't retry flakes in integration tests
  Makefile
Labels: approved, lgtm, ok-to-test

#573 Make conditions sequence test less strict
  test/integration/buildruns_to_taskruns_test.go
Labels: approved, lgtm

#572 Add release.yaml github action
  .github/workflows/release.yaml
Labels: approved, lgtm

#577 Update release.yaml for github actions
  .github/workflows/release.yaml
Labels: approved, lgtm

#562 Use ko for local development and releases
  .ko.yaml
  DEVELOPMENT.md
  Dockerfile
  Makefile
  deploy/operator.yaml
  hack/release.sh
  hack/shipwright-build.sh
  test/e2e/validators.go
Labels: approved, lgtm, ok-to-test

#580 Reflect v0.3.0 in README.md
  README.md
Labels: approved, lgtm

#561 Use go test to run unit tests
  Makefile
Labels: approved, lgtm

#581 Fix travis by installing ko
  .travis.yml
Labels: approved, lgtm, ok-to-test

#567 Proposal: Dedicated Shipwright Operator
  docs/proposals/dedicated-shipwright-operator.md
Labels: approved, kind/design, lgtm

#569 Tweak build operator build settings
  Makefile
Labels: approved, lgtm

#578 Add pprof support to build operator
  Makefile
  cmd/manager/main.go
  docs/profiling.md
  hack/release.sh
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/pprof.go
Labels: approved, discussion, lgtm

#587 Add 502 to list of retryable errors
  test/e2e/validators.go
Labels: approved, lgtm

#588 Remove Dockerfile
  Dockerfile
Labels: approved, lgtm

#582 Generate release.yaml in GitHub Actions release
  .github/workflows/release.yaml
Labels: approved, lgtm, ok-to-test

#583 Publish images without full import path
  Makefile
  hack/release.sh
Labels: approved, lgtm, ok-to-test

#585 add pull request template to integrate with prow release-note plugin
  .github/pull_request_template.md
Labels: approved, lgtm

#592 Fix/nil pointer reference in updateBuildRunUsingTaskRunCondition
  pkg/controller/buildrun/buildrun_controller.go
  pkg/controller/buildrun/buildrun_controller_test.go
Labels: approved, lgtm, release-note

#594 This replaces the taxi go app repo
  docs/build.md
  docs/buildstrategies.md
  pkg/controller/build/build_controller_test.go
  pkg/controller/buildrun/generate_taskrun_test.go
  samples/build/build_buildah_cr.yaml
  samples/build/build_kaniko_cr.yaml
  test/build_samples.go
  test/catalog.go
  test/integration/build_to_buildruns_test.go
  test/integration/build_to_git_test.go
Labels: approved, lgtm, release-note-none

#593 Restructure controllers pkg
  SECURITY.md
  cmd/manager/main.go
  docs/development/testing.md
  docs/proposals/buildstrategy-annotation-propagation.md
  docs/proposals/dedicated-shipwright-operator.md
  docs/proposals/runtime-image.md
  hack/generate-copyright.sh
  pkg/controller/add_build.go
  pkg/controller/add_buildrun.go
  pkg/controller/add_buildstrategy.go
  pkg/controller/add_clusterbuildstrategy.go
  pkg/controller/controller.go
  pkg/controller/utils/utils.go
  pkg/metrics/metrics.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_suite_test.go
  pkg/reconciler/build/build_test.go
  pkg/reconciler/build/controller.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/buildrun_suite_test.go
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/reconciler/buildrun/controller.go
  pkg/reconciler/buildrun/resources/conditions_test.go
  pkg/reconciler/buildrun/resources/credentials.go
  pkg/reconciler/buildrun/resources/credentials_test.go
  pkg/reconciler/buildrun/resources/runtime_image.go
  pkg/reconciler/buildrun/resources/runtime_image_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  pkg/reconciler/buildstrategy/buildstrategy.go
  pkg/reconciler/buildstrategy/buildstrategy_suite_test.go
  pkg/reconciler/buildstrategy/buildstrategy_test.go
  pkg/reconciler/buildstrategy/controller.go
  pkg/reconciler/clusterbuildstrategy/clusterbuildstrategy.go
  pkg/reconciler/clusterbuildstrategy/clusterbuildstrategy_suite_test.go
  pkg/reconciler/clusterbuildstrategy/clusterbuildstrategy_test.go
  pkg/reconciler/clusterbuildstrategy/controller.go
  pkg/reconciler/suite_test.go
  pkg/validate/ownerreferences.go
  pkg/validate/runtime.go
  pkg/validate/secrets.go
  pkg/validate/sourceurl.go
  pkg/validate/strategies.go
  pkg/validate/validate.go
Labels: approved, lgtm, release-note

#598 Add GitHub Action for Sanity Checks
  .github/workflows/sanity-checks.yaml
  pkg/metrics/metrics.go
Labels: approved, lgtm, release-note-none

#597 Improve find for misspell check
  Makefile
Labels: approved, lgtm, release-note-none

#601 Work around current make-install state
  README.md
Labels: approved, lgtm, release-note-none

#605 Remove references to the term "Operator" from README.md
  README.md
Labels: approved, lgtm, release-note-none

#606 Replace operator-sdk/pkg/log imports
  Makefile
  cmd/manager/main.go
  go.mod
  pkg/ctxlog/log.go
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/flags.go
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/logger.go
  vendor/modules.txt
Labels: approved, lgtm, release-note-action-required

#595 Restructure buildrun code into separate resources
  pkg/reconciler/build/build.go
  pkg/reconciler/build/controller.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/controller.go
  pkg/reconciler/buildrun/resources/build.go
  pkg/reconciler/buildrun/resources/build_test.go
  pkg/reconciler/buildrun/resources/conditions.go
  pkg/reconciler/buildrun/resources/conditions_test.go
  pkg/reconciler/buildrun/resources/errors.go
  pkg/reconciler/buildrun/resources/errors_test.go
  pkg/reconciler/buildrun/resources/resources_suite_test.go
  pkg/reconciler/buildrun/resources/service_accounts.go
  pkg/reconciler/buildrun/resources/service_accounts_test.go
  pkg/reconciler/buildrun/resources/strategies.go
  pkg/reconciler/buildrun/resources/strategies_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildstrategy/buildstrategy.go
  pkg/reconciler/buildstrategy/controller.go
  pkg/reconciler/clusterbuildstrategy/clusterbuildstrategy.go
  pkg/reconciler/clusterbuildstrategy/controller.go
  test/catalog.go
Labels: approved, lgtm, release-note

#604 Remove scaffold code from operator-sdk init
  cmd/manager/main.go
  vendor/github.com/coreos/prometheus-operator/LICENSE
  vendor/github.com/coreos/prometheus-operator/NOTICE
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/scheme/doc.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/scheme/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/alertmanager.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/doc.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/generated_expansion.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/monitoring_client.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/podmonitor.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/prometheus.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/prometheusrule.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/servicemonitor.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/thanosruler.go
  vendor/github.com/operator-framework/operator-sdk/pkg/kube-metrics/metrics.go
  vendor/github.com/operator-framework/operator-sdk/pkg/kube-metrics/server.go
  vendor/github.com/operator-framework/operator-sdk/pkg/kube-metrics/store.go
  vendor/github.com/operator-framework/operator-sdk/pkg/kube-metrics/uclient.go
  vendor/github.com/operator-framework/operator-sdk/pkg/metrics/metrics.go
  vendor/github.com/operator-framework/operator-sdk/pkg/metrics/service-monitor.go
  vendor/k8s.io/kube-state-metrics/LICENSE
  vendor/k8s.io/kube-state-metrics/pkg/metric/family.go
  vendor/k8s.io/kube-state-metrics/pkg/metric/generator.go
  vendor/k8s.io/kube-state-metrics/pkg/metric/metric.go
  vendor/k8s.io/kube-state-metrics/pkg/metrics_store/metrics_store.go
  vendor/modules.txt
Labels: approved, lgtm, release-note-none

#611 Use GitHub action for e2e test
  .github/workflows/ci.yml
  .travis.yml
  Makefile
  hack/install-tekton.sh
  test/data/registry.yaml
Labels: approved, lgtm, release-note-none

#614 Improve test stability
  .github/workflows/ci.yml
  .travis.yml
  test/clusterbuildstrategy_samples.go
  test/e2e/samples.go
  test/integration/build_to_buildruns_test.go
  test/integration/buildruns_to_sa_test.go
  test/integration/buildruns_to_taskruns_test.go
  test/integration/buildstrategy_to_taskruns_test.go
  test/integration/clusterbuildstrategy_to_taskruns_test.go
  test/integration/utils/buildruns.go
  test/integration/utils/namespaces.go
Labels: approved, lgtm, release-note-none

#617 Update Kaniko to v1.5.1, leverage --push-retry
  docs/build.md
  docs/buildstrategies.md
  docs/configuration.md
  pkg/config/config.go
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/clusterbuildstrategy_samples.go
Labels: approved, kind/feature, lgtm, release-note

#612 Replace operator-framework/operator-sdk/pkg/ready
  cmd/manager/main.go
  deploy/operator.yaml
  pkg/controller/ready/ready.go
  pkg/controller/ready/ready_suite_test.go
  pkg/controller/ready/ready_test.go
  vendor/github.com/operator-framework/operator-sdk/pkg/ready/ready.go
  vendor/modules.txt
Labels: approved, lgtm, release-note-action-required

#620 update PR template for setting kind label
  .github/pull_request_template.md
Labels: approved, kind/dependency-change, lgtm, release-note-none

#621 Ignore previous logs failure
  .github/workflows/ci.yml
Labels: approved, kind/failing-test, lgtm, release-note-none

#622 Correct and optimize reconciliation on deletion
  pkg/reconciler/build/controller.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/controller.go
  test/integration/buildruns_to_taskruns_test.go
  test/integration/utils/taskruns.go
Labels: approved, kind/bug, lgtm, release-note

#624 Fix sanity check issues
  test/integration/build_to_buildruns_test.go
Labels: approved, kind/failing-test, lgtm, release-note-none

#610 Rename Shipwright components away from "operator"
  .github/workflows/ci.yml
  DEVELOPMENT.md
  HACK.md
  Makefile
  build/Dockerfile
  build/bin/entrypoint
  cmd/manager/main.go
  deploy/100-namespace.yaml
  deploy/200-role.yaml
  deploy/300-rolebinding.yaml
  deploy/400-serviceaccount.yaml
  deploy/500-controller.yaml
  deploy/service_account.yaml
  docs/build.md
  docs/buildstrategies.md
  docs/configuration.md
  docs/development/authentication.md
  docs/development/local_development.md
  docs/development/testing.md
  docs/metrics.md
  docs/profiling.md
  hack/install-tekton.sh
  pkg/config/config.go
  pkg/config/config_test.go
  test/e2e/e2e_suite_test.go
Labels: approved, lgtm, release-note

#603 Add ko build strategy sample
  README.md
  docs/build.md
  docs/buildstrategies.md
  samples/build/build_ko_cr.yaml
  samples/buildrun/buildrun_ko_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
  test/e2e/e2e_test.go
Labels: approved, kind/feature, lgtm, release-note

#627 Fix API version of ko objects
  samples/build/build_ko_cr.yaml
  samples/buildrun/buildrun_ko_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
Labels: approved, kind/bug, lgtm, release-note-none
