Repository shipwright-io/build, pull requests merged in 2022-10, with the labels that each got.

#1117 [Hacktoberfest]: Update Doc to mention support for tokens
  docs/development/authentication.md
Labels: lgtm, approved, kind/documentation, release-note

#1125 Update go.mod packages
  go.mod
  go.sum
  vendor/golang.org/x/net/context/go17.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/trace/trace.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/encoding/htmlindex/tables.go
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/gbk.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/modules.txt
Labels: lgtm, approved, kind/dependency-change, release-note-none

#1128 Fix `G601` findings
  .golangci.yaml
  pkg/reconciler/buildrun/resources/params.go
  pkg/validate/ownerreferences.go
  pkg/volumes/volumes.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#1127 Use `/tekton/home` as `HOME` in strategy steps
  docs/configuration.md
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#1062 Auto-update of tools versions in the sample build strategies
  .github/workflows/check-latest-images.yaml
  hack/check-latest-images.sh
Labels: lgtm, approved, release-note-none
