Repository shipwright-io/build, pull requests merged in 2022-02, with the labels that each got.

#997 Restore files that were temporarily deleted
  hack/release.sh
Labels: lgtm, approved, kind/cleanup, release-note-none

#998 Use YAML document separator in all deploy YAMLs
  deploy/100-namespace.yaml
  deploy/200-role.yaml
  deploy/300-rolebinding.yaml
  deploy/400-serviceaccount.yaml
  deploy/500-controller.yaml
Labels: lgtm, approved, kind/cleanup, release-note-none

#1000 Enhance timeout of waiter
  cmd/waiter/waiter.go
Labels: lgtm, approved, release-note

#999 Improve docs
  docs/build.md
  docs/buildrun.md
  docs/buildstrategies.md
  docs/tutorials/building_with_buildkit.md
  docs/tutorials/building_with_buildpacks.md
  docs/tutorials/building_with_kaniko.md
Labels: lgtm, approved, kind/documentation, release-note-none

#1001 Modernize Buildah sample build strategy
  samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
  test/e2e/e2e_bundle_test.go
  test/e2e/e2e_image_mutate_test.go
  test/e2e/e2e_test.go
  test/e2e/validators_test.go
Labels: kind/feature, lgtm, approved, release-note-action-required

#1002 Enhance release action
  .github/workflows/release.yaml
  README.md
Labels: lgtm, approved, kind/cleanup, release-note-none

#945 CRD usage of pointers vs non-pointers
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/buildstrategy.go
  pkg/apis/build/v1alpha1/source.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/reconciler/buildrun/resources/build_test.go
  pkg/reconciler/buildrun/resources/conditions_test.go
  pkg/reconciler/buildrun/resources/credentials_test.go
  pkg/reconciler/buildrun/resources/failure_details.go
  pkg/reconciler/buildrun/resources/failure_details_test.go
  pkg/reconciler/buildrun/resources/results_test.go
  pkg/reconciler/buildrun/resources/service_accounts.go
  pkg/reconciler/buildrun/resources/sources.go
  pkg/reconciler/buildrun/resources/sources/git.go
  pkg/reconciler/buildrun/resources/sources/git_test.go
  pkg/reconciler/buildrun/resources/sources/utils.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  pkg/validate/buildname.go
  pkg/validate/envvars.go
  pkg/validate/envvars_test.go
  pkg/validate/ownerreferences.go
  pkg/validate/secrets.go
  pkg/validate/sources.go
  pkg/validate/sources_test.go
  pkg/validate/sourceurl.go
  pkg/validate/strategies.go
  test/catalog.go
  test/e2e/common_suite_test.go
  test/e2e/common_test.go
  test/e2e/validators_test.go
  test/integration/build_to_buildruns_test.go
  test/integration/build_to_git_test.go
  test/integration/build_to_secrets_test.go
  test/integration/build_to_taskruns_test.go
  test/integration/buildruns_to_sa_test.go
  test/integration/buildruns_to_taskruns_test.go
  test/integration/buildstrategy_to_taskruns_test.go
  test/utils/builds.go
Labels: lgtm, approved, kind/cleanup, release-note-action-required

#990 Add parameterized CNB_PLATFORM_API to buildpacks strategy
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
Labels: kind/bug, lgtm, approved, release-note

#1006 Replace `quay.io` source-bundle with `ghcr.io`
  cmd/bundle/main_test.go
  pkg/reconciler/buildrun/resources/results_test.go
  test/e2e/e2e_bundle_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#1007 Enable multi-platform builds for BuildKit sample build strategy
  docs/buildstrategies.md
  samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  test/data/build_buildkit_cr_insecure_registry.yaml
  test/e2e/e2e_test.go
  test/e2e/validators_test.go
Labels: kind/feature, lgtm, approved, release-note
