Repository shipwright-io/build, pull requests merged in 2022-03, with the labels that each got.

#1004 Documentation updates
  README.md
  docs/buildstrategies.md
Labels: lgtm, approved, kind/documentation, release-note-none

#1011 Allow setting ginkgo cli path for Makefile tasks
  Makefile
Labels: kind/feature, lgtm, approved, release-note-none

#1015 Add additional versions to image mirror list
  .github/workflows/mirror-images.yaml
Labels: lgtm, approved, kind/dependency-change, release-note-none

#1014 Update Kaniko to 1.8.0, update Trivy to 0.24.4
  docs/buildstrategies.md
  samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/clusterbuildstrategy_samples.go
Labels: lgtm, approved, kind/dependency-change, release-note

#1018 Use quote format specifier where possible
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/reconciler/buildrun/resources/build.go
  pkg/reconciler/buildrun/resources/params.go
  pkg/reconciler/buildrun/resources/sources/http.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#1019 Tweak `Makefile`
  Makefile
Labels: lgtm, approved, kind/cleanup, release-note-none

#1026 Fix BuildKit and BuildAh image digest extraction
  samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
  samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
  test/e2e/e2e_bundle_test.go
  test/e2e/e2e_image_mutate_test.go
  test/e2e/e2e_params_test.go
  test/e2e/e2e_test.go
  test/e2e/validators_test.go
  test/utils/image.go
Labels: kind/bug, lgtm, approved, release-note

#1020 Add source bundle image pruning option
  cmd/bundle/main.go
  cmd/bundle/main_test.go
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  docs/build.md
  pkg/apis/build/v1alpha1/source.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/bundle.go
  pkg/reconciler/buildrun/resources/sources/bundle.go
  test/data/registry.yaml
  test/e2e/common_suite_test.go
  test/e2e/e2e_bundle_test.go
Labels: kind/feature, lgtm, approved, kind/api-change, release-note
