Repository shipwright-io/build, pull requests merged in 2022-01, with the labels that each got.

#930 Surface error results to BuildRun
  .gitignore
  deploy/crds/shipwright.io_buildruns.yaml
  docs/buildrun.md
  docs/buildstrategies.md
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/resources/conditions.go
  pkg/reconciler/buildrun/resources/failure_details.go
  pkg/reconciler/buildrun/resources/failure_details_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
Labels: kind/feature, lgtm, approved, kind/api-change, release-note

#971 Adjust ignore statements for golangci-lint and fix failing tests
  pkg/reconciler/buildrun/resources/conditions.go
  test/integration/build_to_buildruns_test.go
  test/integration/buildruns_to_taskruns_test.go
  test/integration/integration_suite_test.go
  test/utils/taskruns.go
Labels: lgtm, approved, kind/failing-test, release-note-none

#970 Add the list of environments to be blocked on the creation of files inside /platform/env
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
Labels: kind/bug, lgtm, approved, release-note

#974 Add integration test for failure reasons
  pkg/reconciler/buildrun/resources/failure_details.go
  pkg/reconciler/buildrun/resources/failure_details_test.go
  test/buildstrategy_samples.go
  test/integration/buildstrategy_to_taskruns_test.go
Labels: kind/bug, lgtm, approved, release-note-none

#978 Fix failing integration test
  test/integration/buildstrategy_to_taskruns_test.go
Labels: lgtm, approved, kind/failing-test, release-note-none

#977 [BUILD-372] SHIP-0021: Waiter's Base Image
  .github/workflows/base-images.yaml
  images/waiter/Dockerfile
Labels: kind/feature, lgtm, approved, release-note-none

#972 Add git error parser and surfacing of git errors
  cmd/git/main.go
  cmd/git/main_test.go
  docs/buildrun.md
  pkg/git/error_parser.go
  pkg/git/error_parser_test.go
  pkg/reconciler/buildrun/resources/sources/git.go
  pkg/reconciler/buildrun/resources/sources/git_test.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  test/data/build_non_existing_repo.yaml
  test/data/buildrun_non_existing_repo.yaml
  test/e2e/e2e_test.go
Labels: kind/feature, lgtm, approved, release-note-none

#981 Add v0.7.0 release to README
  README.md
Labels: lgtm, approved, kind/documentation, release-note-none

#982 Fix image override bug for mutate-image in config
  pkg/config/config.go
  pkg/config/config_test.go
Labels: kind/bug, lgtm, approved, release-note

#984 Correct controller-gen version in HACK.md
  HACK.md
Labels: lgtm, approved, kind/documentation, release-note-none

#959 Update BuildAh to v1.23.1
  samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
Labels: lgtm, approved, kind/dependency-change, release-note

#989 Turn of parallel tests in test-unit-ginkgo
  Makefile
Labels: lgtm, approved, kind/failing-test, release-note-none

#987 Avoid Unnecessary `go mod vendor`
  Makefile
Labels: lgtm, approved, kind/cleanup, release-note-none

#992 Update Trivy to 0.22.0, update go-containerregistry/crane to 0.8.0
  samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
Labels: lgtm, approved, kind/dependency-change, release-note

#975 SHIP 0025 Extended parameter support
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  deploy/crds/shipwright.io_buildstrategies.yaml
  deploy/crds/shipwright.io_clusterbuildstrategies.yaml
  docs/build.md
  docs/buildrun.md
  docs/buildstrategies.md
  docs/proposals/parameterize-strategies.md
  docs/tutorials/building_with_buildkit.md
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildstrategy.go
  pkg/apis/build/v1alpha1/parameter.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/resources/conditions.go
  pkg/reconciler/buildrun/resources/params.go
  pkg/reconciler/buildrun/resources/params_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/validate/strategies.go
  samples/build/build_buildkit_cr.yaml
  samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  test/build_samples.go
  test/buildrun_samples.go
  test/buildstrategy_samples.go
  test/catalog.go
  test/data/build_buildkit_cr_insecure_registry.yaml
  test/e2e/common_suite_test.go
  test/e2e/e2e_params_test.go
  test/integration/buildstrategy_to_taskruns_test.go
  test/utils/configmaps.go
Labels: kind/feature, lgtm, approved, kind/api-change, release-note-action-required

#996 allow action required release notes
  .github/draft_release_notes.sh
Labels: lgtm, approved, kind/cleanup, release-note-none
