Repository shipwright-io/build, pull requests merged in 2022-04, with the labels that each got.

#1032 Re-add verify-generate target
  .github/workflows/verify.yaml
Labels: lgtm, approved, kind/cleanup, release-note-none

#1016 Support `BuildSpec` in `BuildRun` resources
  README.md
  deploy/crds/shipwright.io_buildruns.yaml
  docs/buildrun.md
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/reconciler/buildrun/resources/build.go
  pkg/reconciler/buildrun/resources/build_test.go
  pkg/reconciler/buildrun/resources/conditions.go
  pkg/reconciler/buildrun/resources/conditions_test.go
  pkg/reconciler/buildrun/resources/service_accounts.go
  pkg/reconciler/buildrun/resources/service_accounts_test.go
  pkg/reconciler/buildrun/resources/strategies_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/validate/buildname.go
  pkg/validate/secrets.go
  pkg/validate/sourceurl.go
  pkg/validate/strategies.go
  pkg/validate/validate.go
  test/catalog.go
  test/e2e/common_suite_test.go
  test/e2e/common_test.go
  test/e2e/e2e_bundle_test.go
  test/e2e/e2e_one_off_builds_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/validators_test.go
  test/utils/environment.go
  test/utils/lookup.go
Labels: kind/feature, lgtm, approved, kind/api-change, release-note

#1034 Run make generate to make files consistent
  deploy/crds/shipwright.io_buildruns.yaml
Labels: lgtm, approved, kind/cleanup, release-note-none

#1025 Add Default RBAC for Non-Admins
  deploy/clusterrole-aggregate-edit.yaml
  deploy/clusterrole-aggregate-view.yaml
  docs/configuration.md
  test/e2e/e2e_rbac_test.go
Labels: kind/feature, lgtm, approved, release-note

#1036 Update Kaniko to 1.8.1, update Trivy to 0.25.3
  docs/buildstrategies.md
  samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/clusterbuildstrategy_samples.go
Labels: lgtm, approved, kind/dependency-change, release-note

#1009 RHDEVDOCS-3863 Prep Shipwright docs for downstream
  docs/build.md
  docs/buildrun.md
Labels: lgtm, approved, kind/documentation, release-note-none

#1027 Support automatic buildrun cleanup
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  docs/build.md
  docs/buildrun.md
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/controller.go
  pkg/reconciler/buildlimitcleanup/build_limit_cleanup.go
  pkg/reconciler/buildlimitcleanup/controller.go
  pkg/reconciler/buildrunttlcleanup/buildrun_ttl_cleanup.go
  pkg/reconciler/buildrunttlcleanup/controller.go
  test/build_samples.go
  test/buildrun_samples.go
  test/clusterbuildstrategy_samples.go
  test/integration/buildrun_cleanup_test.go
  test/utils/buildruns.go
Labels: kind/feature, lgtm, approved, kind/api-change, release-note

#1037 Retrying Wait for Condition
  Makefile
Labels: lgtm, approved, kind/failing-test, release-note-none

#1040 Ensures no external configuration influences tests for git failure diagnostics
  cmd/git/main_test.go
Labels: lgtm, approved, kind/failing-test, release-note-none

#1043 Introduce IBM Container Registry delete
  cmd/bundle/main.go
  cmd/bundle/main_test.go
Labels: kind/bug, kind/feature, lgtm, approved, release-note

#1044 Enable dependabot updates
  .github/dependabot.yml
  .github/workflows/release-notes-linter.yaml
Labels: lgtm, approved, kind/cleanup, release-note-none

#1045 Quote the schedule.time for dependabot config
  .github/dependabot.yml
Labels: kind/bug, lgtm, approved, release-note-none
