Repository shipwright-io/build, pull requests merged in 2022-12, with the labels that each got.

#1163 Remove usage of deprecated Ginkgo capabilities
  Makefile
  test/e2e/e2e_one_off_builds_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#1167 Add base image for image processing command
  .github/workflows/base-images.yaml
  images/image-processing/Dockerfile
Labels: kind/feature, lgtm, approved, release-note-none

#1171 Fix container builds with new UBI9 images
  .github/workflows/ci.yml
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  images/git/Dockerfile
  images/image-processing/Dockerfile
  images/waiter/Dockerfile
Labels: kind/bug, lgtm, approved, release-note-none

#1172 Fix job name duplication
  .github/workflows/base-images.yaml
  .github/workflows/mirror-images.yaml
  .github/workflows/release-notes-linter.yaml
Labels: lgtm, approved, kind/cleanup, release-note-none

#1175 Use different logos depending on preference
  .docs/shipwright-logo-darkbg-512.png
  .docs/shipwright-logo-lightbg-512.png
  README.md
Labels: lgtm, approved, kind/cleanup, release-note-none

#1174 Bump to Go `1.19`
  .github/workflows/check-latest-images.yaml
  .github/workflows/ci.yml
  .github/workflows/mirror-images.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/verify.yaml
  HACK.md
  docs/buildstrategies.md
  go.mod
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  samples/build/build_ko_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
Labels: lgtm, approved, kind/dependency-change, release-note-none
