Repository shipwright-io/build, pull requests merged in 2022-08, with the labels that each got.

#1086 Update base images to UBI 9
  .ko.yaml
  images/git/Dockerfile
  images/waiter/Dockerfile
Labels: lgtm, approved, kind/dependency-change, release-note

#1085 Update GitHub actions
  .github/workflows/base-images.yaml
  .github/workflows/ci.yml
  .github/workflows/mirror-images.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/verify.yaml
Labels: lgtm, approved, kind/dependency-change, release-note-none

#1091 Remove usage of deprecated io/ioutil package
  .github/workflows/verify.yaml
  cmd/bundle/main.go
  cmd/bundle/main_test.go
  cmd/git/main.go
  cmd/git/main_test.go
  cmd/mutate-image/main.go
  cmd/mutate-image/main_test.go
  cmd/shipwright-build-controller/main.go
  hack/install-counterfeiter.sh
  pkg/bundle/bundle_test.go
  test/e2e/validators_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#1092 Fix inconsistent use of `.PHONY` in `Makefile`
  Makefile
Labels: lgtm, approved, release-note-none

#1094 Add coreydaley to OWNERS
  OWNERS
Labels: lgtm, approved, kind/cleanup, release-note-none
