Repository shipwright-io/build, pull requests merged in 2022-05, with the labels that each got.

#1035 Build-273 Volumes support to Build Strategies
  deploy/200-role.yaml
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  deploy/crds/shipwright.io_buildstrategies.yaml
  deploy/crds/shipwright.io_clusterbuildstrategies.yaml
  docs/build.md
  docs/buildrun.md
  docs/buildstrategies.md
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildrun_types.go
  pkg/apis/build/v1alpha1/buildstrategy.go
  pkg/apis/build/v1alpha1/buildstrategy_types.go
  pkg/apis/build/v1alpha1/clusterbuildstrategy_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  pkg/reconciler/buildrun/resources/volumes.go
  pkg/validate/strategies.go
  pkg/validate/volumes.go
  pkg/volumes/volumes.go
  pkg/volumes/volumes_test.go
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/buildstrategy_samples.go
  test/clusterbuildstrategy_samples.go
Labels: kind/feature, lgtm, approved, kind/api-change, release-note-action-required

#1061 Update to Go 1.18
  .github/workflows/ci.yml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/verify.yaml
  HACK.md
  docs/buildstrategies.md
  go.mod
  go.sum
  samples/build/build_ko_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
Labels: lgtm, approved, kind/dependency-change, release-note

#1064 Update BuildAh to 1.23.3
  docs/buildstrategies.md
  samples/buildstrategy/buildah/buildstrategy_buildah_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
Labels: lgtm, approved, kind/dependency-change, release-note

#1065 Fix unit test suite when using Ginkgo
  Makefile
  pkg/env/env_suite_test.go
  pkg/env/env_test.go
  pkg/volumes/volumes_suite_test.go
  pkg/volumes/volumes_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#1068 Expose GOCACHE as volume in ko build strategy
  docs/buildstrategies.md
  samples/build/build_ko_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
Labels: kind/feature, lgtm, approved, release-note

#1054 Bump Tekton
  README.md
  go.mod
  go.sum
  hack/install-tekton.sh
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/default.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/feature_flags.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/pod/affinity_assitant_template.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/pod/template.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/pod/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/openapi_generated.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/param_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pod.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/resolver_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/resource_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/resultref.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/swagger.json
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/task_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskref_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/when_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resource/v1alpha1/pipeline_resource_types.go
  vendor/github.com/tektoncd/pipeline/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/tektoncd/pipeline/pkg/client/clientset/versioned/typed/pipeline/v1alpha1/pipeline_client.go
  vendor/github.com/tektoncd/pipeline/pkg/client/clientset/versioned/typed/pipeline/v1beta1/pipeline_client.go
  vendor/github.com/tektoncd/pipeline/pkg/reconciler/pipeline/dag/dag.go
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/internal/severity/severity.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: lgtm, approved, kind/documentation, kind/dependency-change, release-note

#1072 Update build strategy tools
  samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
Labels: lgtm, approved, kind/dependency-change, release-note-none
