Repository shipwright-io/build, pull requests merged in 2023-09, with the labels that each got.

#1369 Improve BuildAh query
  hack/check-latest-images.sh
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#1371 Add action to clean nightly assets
  .github/workflows/cleanup-nightly-assets.yaml
Labels: size/M, lgtm, approved, kind/cleanup, release-note

#1376 For nightly-cleanup, only preserve last two months
  .github/workflows/cleanup-nightly-assets.yaml
Labels: kind/bug, size/XS, lgtm, approved, release-note-none

#1378 Add missing spec.output.insecure flag to beta API
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  pkg/apis/build/v1beta1/build_conversion.go
  pkg/apis/build/v1beta1/build_types.go
  pkg/apis/build/v1beta1/zz_generated.deepcopy.go
Labels: size/S, lgtm, approved, release-note-none

#1379 Add conversion code for buildrun deletion capability
  pkg/apis/build/v1beta1/build_conversion.go
  pkg/apis/build/v1beta1/build_types.go
  pkg/apis/build/v1beta1/zz_generated.deepcopy.go
  pkg/webhook/conversion/converter_test.go
Labels: kind/feature, size/M, lgtm, approved, release-note-none

#1381 Handle dockerfile in build strategy conversion
  hack/generate-cert.sh
  hack/patch-crds-with-conversion.sh
  pkg/apis/build/v1beta1/build_conversion.go
  pkg/apis/build/v1beta1/buildrun_conversion.go
  pkg/apis/build/v1beta1/buildstrategy_conversion.go
  pkg/apis/build/v1beta1/clusterbuildstrategy_conversion.go
  pkg/webhook/conversion/converter.go
  pkg/webhook/conversion/converter_test.go
Labels: kind/feature, size/L, lgtm, approved, release-note-none

#1370 Run buildah steps without privileged containers
  pkg/reconciler/buildrun/resources/taskrun_test.go
  samples/buildstrategy/buildah/buildstrategy_buildah_shipwright_managed_push_cr.yaml
  samples/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
  test/buildstrategy_samples.go
  test/clusterbuildstrategy_samples.go
Labels: kind/feature, size/M, lgtm, approved, release-note

#1386 Ensure assets deletion use a sleep time
  .github/workflows/cleanup-nightly-assets.yaml
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#1387 chore: import packages only once
  pkg/validate/volumes.go
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#1384 Update release process for webhook certificate
  .github/workflows/ci.yml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/verify.yaml
  Makefile
  README.md
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  deploy/crds/shipwright.io_buildstrategies.yaml
  deploy/crds/shipwright.io_clusterbuildstrategies.yaml
  hack/customization/conversion_webhook_block.yaml
  hack/patch-crds-with-conversion.sh
  hack/release.sh
  hack/setup-webhook-cert-integration-test.sh
  hack/setup-webhook-cert.sh
  test/integration/integration_suite_test.go
  test/utils/environment.go
  test/utils/namespaces.go
  test/utils/webhook.go
Labels: kind/feature, size/L, lgtm, approved, release-note
