Repository shipwright-io/build, pull requests merged in 2023-06, with the labels that each got.

#1311 Move prune logic to image package
  cmd/bundle/main.go
  cmd/bundle/main_test.go
  pkg/image/delete.go
  pkg/image/delete_test.go
  test/utils/gomega.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#1316 Pulls ginkgo version as per go.mod instead of latest
  Makefile
Labels: lgtm, approved, kind/cleanup, release-note-none

#1315 Adds `--server-side` to `ko apply` as well
  Makefile
Labels: lgtm, approved, release-note-none

#1321 Use tag name instead of release name
  hack/check-latest-images.sh
Labels: lgtm, approved, kind/failing-test, release-note-none

#1318 Add steps for running on OpenShift
  README.md
Labels: lgtm, approved, release-note-none

#1268 SHIP-0036: Part 1: Update base images to allow an arbitrary user to run it
  .github/workflows/base-images.yaml
  .github/workflows/ci.yml
  images/base/Dockerfile
  images/docker-bake.hcl
  images/git/Dockerfile
  images/image-processing/Dockerfile
  images/waiter/Dockerfile
Labels: kind/feature, lgtm, approved, release-note

#1266 SHIP-0036: Part 2: Introduce securityContext for build strategy spec
  .ko.yaml
  cmd/git/main.go
  deploy/crds/shipwright.io_buildstrategies.yaml
  deploy/crds/shipwright.io_clusterbuildstrategies.yaml
  docs/buildstrategies.md
  docs/configuration.md
  pkg/apis/build/v1alpha1/buildstrategy.go
  pkg/apis/build/v1alpha1/buildstrategy_types.go
  pkg/apis/build/v1alpha1/clusterbuildstrategy_types.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/build/v1beta1/buildstrategy.go
  pkg/apis/build/v1beta1/buildstrategy_types.go
  pkg/apis/build/v1beta1/clusterbuildstrategy_types.go
  pkg/apis/build/v1beta1/zz_generated.deepcopy.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/reconciler/buildrun/resources/steps/security_context.go
  pkg/reconciler/buildrun/resources/steps/security_context_test.go
  pkg/reconciler/buildrun/resources/steps/steps_suite_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  samples/buildstrategy/buildah/buildstrategy_buildah_shipwright_managed_push_cr.yaml
  samples/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
  samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/utils/gomega.go
Labels: kind/feature, lgtm, approved, kind/api-change, release-note

#1323 Update Buildpacks strategy
  samples/build/build_buildpacks-v3-heroku_cr.yaml
  samples/build/build_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
Labels: kind/feature, lgtm, approved, release-note
