Repository shipwright-io/build, pull requests merged in 2023-10, with the labels that each got.

#1390 Reliably detect evicted pods for failing BuildRuns
  pkg/reconciler/buildrun/resources/conditions.go
Labels: kind/bug, size/S, lgtm, approved, release-note

#1398 Removing Strategy.APIversion
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  pkg/apis/build/v1beta1/build_conversion.go
  pkg/apis/build/v1beta1/buildstrategy.go
  pkg/apis/build/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, size/S, lgtm, approved, release-note

#1402 Sanitize file target paths
  pkg/bundle/bundle.go
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#1352 Modifying the sample examples to refer v1beta1
  docs/build.md
  docs/buildrun.md
  docs/buildstrategies.md
  docs/development/authentication.md
  docs/development/testing.md
  docs/tutorials/building_with_buildkit.md
  docs/tutorials/building_with_buildpacks.md
  docs/tutorials/building_with_kaniko.md
  samples/build/build_buildah_shipwright_managed_push_cr.yaml
  samples/build/build_buildah_strategy_managed_push_cr.yaml
  samples/build/build_buildkit_cr.yaml
  samples/build/build_buildpacks-v3-heroku_cr.yaml
  samples/build/build_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/build/build_buildpacks-v3_cr.yaml
  samples/build/build_buildpacks-v3_namespaced_cr.yaml
  samples/build/build_kaniko-trivy-bad_cr.yaml
  samples/build/build_kaniko-trivy-good_cr.yaml
  samples/build/build_kaniko_cr.yaml
  samples/build/build_ko_cr.yaml
  samples/build/build_source-to-image_cr.yaml
  samples/buildrun/buildrun_buildah_cr.yaml
  samples/buildrun/buildrun_buildkit_cr.yaml
  samples/buildrun/buildrun_buildpacks-v3-heroku_cr.yaml
  samples/buildrun/buildrun_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildrun/buildrun_buildpacks-v3_cr.yaml
  samples/buildrun/buildrun_buildpacks-v3_namespaced_cr.yaml
  samples/buildrun/buildrun_kaniko-trivy-bad_cr.yaml
  samples/buildrun/buildrun_kaniko-trivy-good_cr.yaml
  samples/buildrun/buildrun_kaniko_cr.yaml
  samples/buildrun/buildrun_ko_cr.yaml
  samples/buildrun/buildrun_source-to-image_cr.yaml
  samples/buildstrategy/buildah/buildstrategy_buildah_shipwright_managed_push_cr.yaml
  samples/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
  samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
Labels: size/XL, kind/documentation, release-note-none

#1405 Update references to build strategies to v1beta1
  docs/build.md
  docs/buildstrategies.md
  hack/release.sh
Labels: size/M, lgtm, approved, kind/cleanup, release-note-none

#1408 Add missing type to CRs
  docs/build.md
  docs/buildrun.md
  samples/v1beta1/build/build_buildah_shipwright_managed_push_cr.yaml
  samples/v1beta1/build/build_buildah_strategy_managed_push_cr.yaml
  samples/v1beta1/build/build_buildkit_cr.yaml
  samples/v1beta1/build/build_buildpacks-v3-heroku_cr.yaml
  samples/v1beta1/build/build_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/v1beta1/build/build_buildpacks-v3_cr.yaml
  samples/v1beta1/build/build_buildpacks-v3_namespaced_cr.yaml
  samples/v1beta1/build/build_kaniko-trivy-bad_cr.yaml
  samples/v1beta1/build/build_kaniko-trivy-good_cr.yaml
  samples/v1beta1/build/build_kaniko_cr.yaml
  samples/v1beta1/build/build_ko_cr.yaml
  samples/v1beta1/build/build_source-to-image_cr.yaml
  test/v1beta1_samples/build_samples.go
Labels: size/M, lgtm, approved, kind/documentation, release-note-none

#1407 Package k8s.io/utils/pointer conflict
  go.mod
  go.sum
  pkg/apis/build/v1beta1/build_conversion.go
  pkg/apis/build/v1beta1/buildrun_conversion.go
  pkg/apis/build/v1beta1/buildstrategy_conversion.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/reconciler/buildrun/resources/credentials_test.go
  pkg/reconciler/buildrun/resources/params_test.go
  pkg/reconciler/buildrun/resources/results_test.go
  pkg/reconciler/buildrun/resources/service_accounts.go
  pkg/reconciler/buildrun/resources/sources/git_test.go
  pkg/reconciler/buildrun/resources/sources/utils.go
  pkg/reconciler/buildrun/resources/steps/security_context.go
  pkg/reconciler/buildrun/resources/steps/security_context_test.go
  pkg/validate/buildname.go
  pkg/validate/envvars.go
  pkg/validate/envvars_test.go
  pkg/validate/ownerreferences.go
  pkg/validate/params_test.go
  pkg/validate/secrets.go
  pkg/validate/sourceurl.go
  pkg/validate/strategies.go
  pkg/validate/trigger.go
  pkg/webhook/conversion/converter_test.go
  test/e2e/v1alpha1/common_suite_test.go
  test/e2e/v1alpha1/e2e_params_test.go
  test/e2e/v1alpha1/validators_test.go
  test/e2e/v1beta1/common_suite_test.go
  test/e2e/v1beta1/e2e_params_test.go
  test/integration/build_to_git_test.go
  test/v1alpha1_samples/catalog.go
  test/v1beta1_samples/catalog.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/OWNERS
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: kind/bug, size/L, lgtm, approved, release-note

#1403 Ensure conversion for local source takes place
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  docs/buildrun.md
  pkg/apis/build/v1alpha1/source.go
  pkg/apis/build/v1beta1/build_conversion.go
  pkg/apis/build/v1beta1/buildrun_conversion.go
  pkg/apis/build/v1beta1/buildrun_types.go
  pkg/apis/build/v1beta1/buildstrategy_conversion.go
  pkg/apis/build/v1beta1/source.go
  pkg/apis/build/v1beta1/zz_generated.deepcopy.go
  pkg/webhook/conversion/converter_test.go
  test/e2e/v1beta1/common_suite_test.go
  test/e2e/v1beta1/validators_test.go
  test/v1beta1_samples/catalog.go
Labels: lgtm, approved, size/XL, kind/documentation, kind/design, kind/api-change, release-note

#1410 Omit empty output object in BuildRun spec
  pkg/apis/build/v1beta1/buildrun_conversion.go
  pkg/webhook/conversion/converter_test.go
  test/utils/v1beta1/image.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none
