Repository shipwright-io/build, pull requests merged in 2023-02, with the labels that each got.

#1190 Adjust CURRENT_TAG logic
  hack/check-latest-images.sh
Labels: lgtm, approved, kind/cleanup, release-note-none

#1203 Update OWNERS - Remove coreydaley
  OWNERS
Labels: lgtm, approved, release-note-none

#1196 Mark BuildSpec volume description field as deprecated
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  docs/build.md
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1alpha1/buildstrategy.go
  pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  pkg/volumes/volumes_test.go
Labels: lgtm, approved, api, kind/documentation, release-note

#1207 Remove unneeded find path
  hack/generate-copyright.sh
Labels: lgtm, approved, kind/cleanup, release-note-none

#1219 Allow non-current user to own the directory which is built by ko
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
Labels: kind/bug, lgtm, approved, release-note
