Repository shipwright-io/build, pull requests merged in 2023-11, with the labels that each got.

#1416 Fix `G402` reports with latest `gosec` version
  pkg/image/options.go
  test/utils/v1alpha1/webhook.go
  test/utils/v1beta1/webhook.go
  test/utils/webhook.go
Labels: size/L, lgtm, approved, release-note-none

#1422 Add e2e test for v1beta1-localsource
  docs/build.md
  test/data/v1beta1/buildrun_buildah_cr_local_source_upload.yaml
  test/e2e/v1beta1/e2e_local_source_upload_test.go
Labels: size/L, lgtm, approved, kind/cleanup, release-note-none

#1429 Allow a file or directory having a name with two subsequent dots while still preventing path traversal
  pkg/bundle/bundle.go
Labels: kind/bug, size/XS, lgtm, approved, release-note

#1432 Cleanup Buildpacks strategies
  docs/buildstrategies.md
  pkg/reconciler/buildrun/resources/taskrun_test.go
  samples/v1alpha1/buildstrategy/buildstrategy/buildah/buildstrategy_buildah_shipwright_managed_push_cr.yaml
  samples/v1alpha1/buildstrategy/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
  samples/v1alpha1/buildstrategy/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/v1alpha1/buildstrategy/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/v1alpha1/buildstrategy/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/v1alpha1/buildstrategy/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_cr.yaml
  samples/v1alpha1/buildstrategy/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3_namespaced_cr.yaml
  samples/v1alpha1/buildstrategy/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
  samples/v1alpha1/buildstrategy/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/v1alpha1/buildstrategy/buildstrategy/ko/buildstrategy_ko_cr.yaml
  samples/v1alpha1/buildstrategy/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
  samples/v1alpha1/buildstrategy/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/v1alpha1_samples/build_samples.go
  test/v1beta1_samples/build_samples.go
Labels: lgtm, approved, size/XXL, kind/cleanup, release-note-none

#1435 Use Tekton V1 API when working with TaskRuns
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controller/controller.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/reconciler/buildrun/controller.go
  pkg/reconciler/buildrun/resources/conditions.go
  pkg/reconciler/buildrun/resources/conditions_test.go
  pkg/reconciler/buildrun/resources/failure_details.go
  pkg/reconciler/buildrun/resources/failure_details_test.go
  pkg/reconciler/buildrun/resources/image_processing.go
  pkg/reconciler/buildrun/resources/image_processing_test.go
  pkg/reconciler/buildrun/resources/params.go
  pkg/reconciler/buildrun/resources/params_test.go
  pkg/reconciler/buildrun/resources/results.go
  pkg/reconciler/buildrun/resources/results_test.go
  pkg/reconciler/buildrun/resources/sources.go
  pkg/reconciler/buildrun/resources/sources/bundle.go
  pkg/reconciler/buildrun/resources/sources/git.go
  pkg/reconciler/buildrun/resources/sources/git_test.go
  pkg/reconciler/buildrun/resources/sources/http.go
  pkg/reconciler/buildrun/resources/sources/http_test.go
  pkg/reconciler/buildrun/resources/sources/local_copy.go
  pkg/reconciler/buildrun/resources/sources/local_copy_test.go
  pkg/reconciler/buildrun/resources/sources/utils.go
  pkg/reconciler/buildrun/resources/sources/utils_test.go
  pkg/reconciler/buildrun/resources/steps/security_context.go
  pkg/reconciler/buildrun/resources/steps/security_context_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  pkg/reconciler/buildrun/resources/volumes.go
  test/e2e/v1alpha1/validators_test.go
  test/e2e/v1beta1/validators_test.go
  test/integration/buildruns_to_taskruns_test.go
  test/integration/buildstrategy_to_taskruns_test.go
  test/utils/v1alpha1/lookup.go
  test/utils/v1alpha1/taskruns.go
  test/utils/v1beta1/lookup.go
  test/utils/v1beta1/taskruns.go
  test/v1alpha1_samples/catalog.go
  test/v1beta1_samples/catalog.go
Labels: kind/feature, lgtm, approved, size/XL, release-note
