Repository shipwright-io/build, pull requests merged in 2023-01, with the labels that each got.

#1176 Add custom error for basic auth with HTTP
  cmd/git/main.go
  cmd/git/main_suite_test.go
  cmd/git/main_test.go
  go.sum
  pkg/git/error_parser.go
Labels: kind/bug, lgtm, approved, release-note

#1179 Update OWNERS
  OWNERS
Labels: lgtm, approved, release-note-none

#1182 Update setup-kubectl action from v1 to v3
  .github/workflows/ci.yml
Labels: lgtm, approved, kind/dependency-change, release-note-none

#1183 Replace deprecated set-output by GITHUB_OUTPUT
  .github/workflows/nightly.yaml
Labels: lgtm, approved, kind/cleanup, release-note-none

#1181 Fix build strategy image update
  hack/check-latest-images.sh
Labels: lgtm, approved, kind/cleanup, release-note-none

#1187 Include pkg directory
  .github/workflows/check-latest-images.yaml
Labels: lgtm, approved, kind/failing-test, release-note-none
