Repository shipwright-io/build, pull requests merged in 2023-08, with the labels that each got.

#1351 Update to Golang 1.20
  .github/workflows/ci.yml
  .github/workflows/mirror-images.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/verify.yaml
  HACK.md
  docs/buildstrategies.md
  go.mod
  samples/build/build_ko_cr.yaml
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
Labels: lgtm, approved, kind/dependency-change, release-note

#1353 Add issues workflow and clean up repository
  .github/pull_request_template.md
  .github/workflows/issues.yml
  2021-roadmap.md
  CONTRIBUTING.md
  SECURITY.md
  code-of-conduct.md
Labels: lgtm, approved, kind/cleanup, release-note-none

#1361 Use --snapshot-mode instead of --snapshotMode and --tar-path instead --tarPath in sample build strategies that use Kaniko
  docs/buildstrategies.md
  samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
  samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/buildstrategy/source-to-image/buildstrategy_source-to-image_cr.yaml
  test/clusterbuildstrategy_samples.go
Labels: size/S, lgtm, approved, kind/cleanup, release-note

#1364 Fix broken link
  README.md
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#1365 Use -p flag with mkdir
  Makefile
Labels: kind/bug, size/XS, lgtm, approved, release-note-none

#1362 Use BuildKit's option to not tar the output image as OCI layout as we need it as a directory anyway
  samples/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
Labels: size/XS, lgtm, approved, release-note
