Repository shipwright-io/build, pull requests merged in 2023-04, with the labels that each got.

#1262 Add `platform` to `install-controller-kind` target
  Makefile
Labels: kind/bug, lgtm, approved, release-note-none

#1272 Fix remaining reference to `mutate-image`
  pkg/config/config_test.go
  pkg/reconciler/buildrun/resources/image_processing.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  test/integration/build_to_taskruns_test.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#1273 Replace `LayerFromReader` with `LayerFromOpener` in bundle package
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
Labels: lgtm, approved, release-note-none

#1276 Improve logging in error case for pod retrieval
  pkg/reconciler/buildrun/resources/conditions.go
  pkg/reconciler/buildrun/resources/failure_details.go
Labels: lgtm, approved, kind/cleanup, release-note-none

#1277 Pass platform to ko build
  samples/buildstrategy/ko/buildstrategy_ko_cr.yaml
Labels: kind/bug, lgtm, approved, release-note
