Repository shipwright-io/build, pull requests merged in 2024-07, with the labels that each got.

#1632 docs: fix broken links, tables and typos
  DEVELOPMENT.md
  README.md
  docs/build.md
  docs/buildrun.md
  docs/buildstrategies.md
  docs/configuration.md
  docs/development/authentication.md
  docs/development/testing.md
  docs/metrics.md
  docs/profiling.md
  docs/tutorials/README.md
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#1645 Pin to newer Node version that is still supported by Paketo
  test/e2e/v1alpha1/common_suite_test.go
  test/e2e/v1alpha1/e2e_image_mutate_test.go
  test/e2e/v1beta1/common_suite_test.go
  test/e2e/v1beta1/e2e_image_mutate_test.go
Labels: size/S, lgtm, approved, kind/failing-test, release-note-none

#1649 Test two different Tekton versions in e2e and integration tests
  .github/workflows/ci.yml
Labels: size/S, lgtm, approved, kind/cleanup, release-note

#1650 fixed container name for shipwright-webhook
  deploy/700-deployment-webhook.yaml
Labels: size/XS, lgtm, approved, release-note-none
