Repository shipwright-io/build, pull requests merged in 2024-03, with the labels that each got.

#1517 [fixed] : broken invite link of public calender
  README.md
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#1519 Minor fixes on docs and types
  docs/build.md
  docs/buildrun.md
  pkg/apis/build/v1beta1/source.go
Labels: size/S, lgtm, approved, kind/documentation, release-note-none

#1516 Include GitHub action version in Dependabot setup
  .github/dependabot.yml
Labels: size/XS, lgtm, approved, kind/dependency-change, release-note-none

#1536 Ensure curl cmd follows redirection
  README.md
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#1534 Fix unknown strategy kind reconcile issue
  pkg/apis/build/v1beta1/build_types.go
  pkg/reconciler/build/build_test.go
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/validate/strategies.go
  pkg/validate/strategies_test.go
  pkg/validate/validate.go
  test/integration/build_to_buildruns_test.go
  test/integration/buildruns_to_taskruns_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none

#1538 Use major version for `peter-evans/create-pull-request` action
  .github/workflows/check-latest-images.yaml
  .github/workflows/release.yaml
Labels: size/XS, lgtm, approved, kind/dependency-change, release-note-none

#1535 Move README to v1beta1
  README.md
Labels: size/S, lgtm, approved, kind/documentation, release-note-none

#1541 SHIP-0038: Run CI on Release Branches
  .github/workflows/ci.yml
  .github/workflows/release-notes-linter.yaml
  .github/workflows/verify.yaml
Labels: lgtm, approved, kind/cleanup

#1547 Fix golangci-lint errors for CI
  pkg/image/options.go
  pkg/reconciler/build/controller.go
  pkg/reconciler/buildlimitcleanup/controller.go
  pkg/reconciler/buildrun/controller.go
  pkg/reconciler/buildrunttlcleanup/controller.go
  test/utils/v1alpha1/webhook.go
  test/utils/v1beta1/webhook.go
  test/utils/webhook.go
Labels: size/M, lgtm, approved, kind/cleanup, release-note-none

#1543 [release-v0.12] SHIP-0038: Run CI on Release Branches
  .github/workflows/ci.yml
  .github/workflows/release-notes-linter.yaml
  .github/workflows/verify.yaml
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#1552 Improve conversion webhook logging
  pkg/apis/build/v1beta1/build_conversion.go
  pkg/apis/build/v1beta1/buildrun_conversion.go
  pkg/apis/build/v1beta1/buildstrategy_conversion.go
  pkg/apis/build/v1beta1/clusterbuildstrategy_conversion.go
  pkg/webhook/conversion/conversion.go
  pkg/webhook/conversion/converter.go
Labels: size/S, lgtm, approved, kind/cleanup, release-note

#1557 SHIP-0038: Add Git Ref to Release Workflow
  .github/workflows/release.yaml
Labels: size/S, lgtm, approved, kind/cleanup, release-note-none

#1556 Release Branch Workflow
  .github/workflows/release-branch.yml
Labels: size/S, lgtm, approved, kind/cleanup, release-note-none

#1559 Fix underscore showing up between badges
  README.md
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none
