Repository shipwright-io/build, pull requests merged in 2024-12, with the labels that each got.

#1743 Update tutorial add spec.source.type to the example build definitions
  docs/tutorials/building_with_buildkit.md
  docs/tutorials/building_with_buildpacks.md
  docs/tutorials/building_with_kaniko.md
Labels: documentation, size/XS, lgtm, approved, release-note-none

#1733 Add automation to trigger automatic updates of the BuildKit image in our sample build strategies
  .github/workflows/check-latest-images.yaml
  hack/check-latest-images.sh
Labels: kind/feature, size/XS, lgtm, approved, release-note-none

#1746 Correct regex that selects the lines with image changes
  .github/workflows/check-latest-images.yaml
Labels: kind/bug, size/XS, lgtm, approved, release-note-none

#1750 Add file listing environment variables to documentation
  docs/configuration.md
  pkg/config/config.go
  pkg/config/config_test.go
Labels: size/M, lgtm, approved, kind/documentation, release-note-none
