Repository shipwright-io/build, pull requests merged in 2024-02, with the labels that each got.

#1486 Fix the BuildRun conversion from alpha to beta when .spec.serviceAccount.generate=true
  pkg/apis/build/v1beta1/buildrun_conversion.go
  pkg/webhook/conversion/converter_test.go
Labels: kind/bug, size/M, lgtm, approved, release-note

#1494 Fix golangci-lint findings
  pkg/reconciler/build/controller.go
  pkg/reconciler/buildlimitcleanup/controller.go
  pkg/reconciler/buildrun/controller.go
  pkg/reconciler/buildrunttlcleanup/controller.go
Labels: size/S, lgtm, approved, kind/cleanup, release-note-none

#1495 Update Go to 1.21, ko to 1.15.1, KinD to 0.21
  .github/workflows/ci.yml
  .github/workflows/mirror-images.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/verify.yaml
  HACK.md
  docs/buildstrategies.md
  go.mod
  go.sum
  hack/install-kind.sh
  samples/v1alpha1/build/build_ko_cr.yaml
  samples/v1alpha1/buildstrategy/ko/buildstrategy_ko_cr.yaml
  samples/v1beta1/build/build_ko_cr.yaml
  samples/v1beta1/buildstrategy/ko/buildstrategy_ko_cr.yaml
Labels: size/M, lgtm, approved, kind/dependency-change, release-note

#1506 Fixed buildCredentialserences function name
  pkg/validate/secrets.go
Labels: size/XS, lgtm, approved, release-note-none

#1511 Fix Heruko buildpacks samples that failed to determine the target OS
  samples/v1alpha1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/v1alpha1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
  samples/v1beta1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_cr.yaml
  samples/v1beta1/buildstrategy/buildpacks-v3/buildstrategy_buildpacks-v3-heroku_namespaced_cr.yaml
Labels: size/M, lgtm, approved, kind/failing-test, release-note-none

#1510 [fixed] : Order of Local Source between Builds and BuildRuns
  pkg/reconciler/buildrun/resources/sources.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none
