Repository shipwright-io/build, pull requests merged in 2024-04, with the labels that each got.

#1566 Correct multiple secret values in one array parameter that references different secret variables
  .gitignore
  pkg/reconciler/buildrun/resources/params.go
  pkg/reconciler/buildrun/resources/params_test.go
Labels: kind/bug, size/M, lgtm, approved, release-note

#1565 Release Workflow Fixes
  .github/workflows/release.yaml
Labels: size/S, lgtm, approved, kind/cleanup, release-note-none

#1569 Do not set dockerfile parameter to an empty string to align with behavior of alpha controller
  pkg/apis/build/v1beta1/build_conversion.go
Labels: kind/bug, size/XS, lgtm, approved, release-note
