Repository shipwright-io/build, pull requests merged in 2024-08, with the labels that each got.

#1646 Add script for storage version migartion of crds
  README.md
  deploy/200-role.yaml
  hack/storage-version-migration.sh
Labels: kind/feature, size/L, lgtm, approved, release-note

#1634 Native multi-arch ClusterBuildStrategy
  Makefile
  samples/v1beta1/buildstrategy/multiarch-native-buildah/buildstrategy_multiarch_native_buildah_cr.yaml
  samples/v1beta1/buildstrategy/multiarch-native-buildah/role_multiarch_native_buildah_cr.yaml
  samples/v1beta1/buildstrategy/multiarch-native-buildah/rolebinding_multiarch_native_buildah_cr.yaml
  samples/v1beta1/buildstrategy/multiarch-native-buildah/rolebinding_multiarch_native_buildah_scc_okd_cr.yaml
  test/data/v1beta1/build_multiarch_native_buildah_cr.yaml
  test/data/v1beta1/buildrun_multiarch_native_buildah_cr.yaml
  test/e2e/v1alpha1/e2e_test.go
  test/e2e/v1alpha1/validators_test.go
  test/e2e/v1beta1/e2e_test.go
  test/e2e/v1beta1/validators_test.go
Labels: lgtm, approved, size/XL, release-note

#1657 Add automation to bump Tekton automatically
  .github/bump-tekton-lts.sh
  .github/workflows/ci.yml
  .github/workflows/update-tekton-version.yaml
  README.md
Labels: kind/feature, size/L, lgtm, approved, release-note-none

#1661 Use dedicated token for the workflow that bumps the Tekton version
  .github/workflows/update-tekton-version.yaml
Labels: size/S, lgtm, approved, kind/cleanup, release-note-none

#1666 Change to errors.New because strings passed to fmt.Errorf should be constants according to govet
  pkg/image/delete.go
Labels: size/XS, lgtm, approved, kind/failing-test, release-note-none

#1660 Documentation for the multiarch-native-buildah ClusterStrategy
  docs/buildstrategies.md
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#1670 Address G115 findings
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  pkg/apis/build/v1beta1/build_types.go
  pkg/bundle/bundle.go
  pkg/reconciler/buildlimitcleanup/build_limit_cleanup.go
  pkg/reconciler/buildlimitcleanup/controller.go
Labels: size/M, lgtm, approved, kind/failing-test, release-note-none
