Repository shipwright-io/build, pull requests merged in 2024-10, with the labels that each got.

#1683 Add NodeSelectors to Build and BuildRun objects
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  docs/build.md
  docs/buildrun.md
  pkg/apis/build/v1beta1/build_types.go
  pkg/apis/build/v1beta1/buildrun_types.go
  pkg/apis/build/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  pkg/validate/nodeselector.go
  pkg/validate/validate.go
  test/integration/build_to_taskruns_test.go
  test/integration/buildruns_to_taskruns_test.go
  test/v1beta1_samples/build_samples.go
  test/v1beta1_samples/buildrun_samples.go
Labels: kind/feature, size/L, lgtm, approved, release-note

#1703 Fix container template names in docs
  docs/configuration.md
Labels: size/XS, lgtm, approved, kind/documentation, kind/cleanup, release-note-none

#1700 Retry trivy when it fails to download the vulnerability database due to rate-limiting
  pkg/image/vulnerability_scan.go
Labels: kind/bug, size/M, lgtm, approved, kind/flake, release-note

#1699 Fix issue with non-writable sub-directories
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
Labels: kind/bug, size/M, lgtm, approved, release-note

#1701 Fix flaky test case
  test/integration/build_to_buildruns_test.go
Labels: size/M, lgtm, approved, kind/flake, release-note-none

#1698 Configure commit author, signing and signoff in GitHub action for image updates
  .github/workflows/check-latest-images.yaml
Labels: size/S, lgtm, approved, kind/cleanup, release-note-none

#1702 Add file listing for bundle unpack and Git clone
  cmd/bundle/main.go
  cmd/bundle/main_test.go
  cmd/git/main.go
  cmd/git/main_test.go
  go.mod
  go.sum
  pkg/util/filelisting.go
  pkg/util/util.go
  vendor/github.com/jedib0t/go-pretty/v6/LICENSE
  vendor/github.com/jedib0t/go-pretty/v6/table/README.md
  vendor/github.com/jedib0t/go-pretty/v6/table/config.go
  vendor/github.com/jedib0t/go-pretty/v6/table/pager.go
  vendor/github.com/jedib0t/go-pretty/v6/table/pager_options.go
  vendor/github.com/jedib0t/go-pretty/v6/table/render.go
  vendor/github.com/jedib0t/go-pretty/v6/table/render_csv.go
  vendor/github.com/jedib0t/go-pretty/v6/table/render_hint.go
  vendor/github.com/jedib0t/go-pretty/v6/table/render_html.go
  vendor/github.com/jedib0t/go-pretty/v6/table/render_init.go
  vendor/github.com/jedib0t/go-pretty/v6/table/render_markdown.go
  vendor/github.com/jedib0t/go-pretty/v6/table/render_tsv.go
  vendor/github.com/jedib0t/go-pretty/v6/table/sort.go
  vendor/github.com/jedib0t/go-pretty/v6/table/style.go
  vendor/github.com/jedib0t/go-pretty/v6/table/table.go
  vendor/github.com/jedib0t/go-pretty/v6/table/util.go
  vendor/github.com/jedib0t/go-pretty/v6/table/writer.go
  vendor/github.com/jedib0t/go-pretty/v6/text/README.md
  vendor/github.com/jedib0t/go-pretty/v6/text/align.go
  vendor/github.com/jedib0t/go-pretty/v6/text/ansi.go
  vendor/github.com/jedib0t/go-pretty/v6/text/ansi_unix.go
  vendor/github.com/jedib0t/go-pretty/v6/text/ansi_windows.go
  vendor/github.com/jedib0t/go-pretty/v6/text/color.go
  vendor/github.com/jedib0t/go-pretty/v6/text/color_html.go
  vendor/github.com/jedib0t/go-pretty/v6/text/cursor.go
  vendor/github.com/jedib0t/go-pretty/v6/text/direction.go
  vendor/github.com/jedib0t/go-pretty/v6/text/escape_seq_parser.go
  vendor/github.com/jedib0t/go-pretty/v6/text/filter.go
  vendor/github.com/jedib0t/go-pretty/v6/text/format.go
  vendor/github.com/jedib0t/go-pretty/v6/text/hyperlink.go
  vendor/github.com/jedib0t/go-pretty/v6/text/string.go
  vendor/github.com/jedib0t/go-pretty/v6/text/transformer.go
  vendor/github.com/jedib0t/go-pretty/v6/text/valign.go
  vendor/github.com/jedib0t/go-pretty/v6/text/wrap.go
  vendor/github.com/mattn/go-runewidth/LICENSE
  vendor/github.com/mattn/go-runewidth/README.md
  vendor/github.com/mattn/go-runewidth/runewidth.go
  vendor/github.com/mattn/go-runewidth/runewidth_appengine.go
  vendor/github.com/mattn/go-runewidth/runewidth_js.go
  vendor/github.com/mattn/go-runewidth/runewidth_posix.go
  vendor/github.com/mattn/go-runewidth/runewidth_table.go
  vendor/github.com/mattn/go-runewidth/runewidth_windows.go
  vendor/github.com/rivo/uniseg/LICENSE.txt
  vendor/github.com/rivo/uniseg/README.md
  vendor/github.com/rivo/uniseg/doc.go
  vendor/github.com/rivo/uniseg/grapheme.go
  vendor/github.com/rivo/uniseg/properties.go
  vendor/modules.txt
Labels: kind/feature, size/L, lgtm, approved, release-note

#1694 Add GitHub action that checks the latest release for vulnerabilities and reports them in an issue
  .github/report-release-vulnerabilities.sh
  .github/workflows/report-release-vulnerabilities.yaml
Labels: kind/feature, size/L, lgtm, approved, release-note-none

#1708 Use `--vv` and `--trace` in E2E
  Makefile
Labels: size/XS, lgtm, approved, kind/flake, release-note-none

#1709 Set Build to empty object because GetBuildObject will fill but not initialize it
  test/e2e/v1beta1/common_test.go
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none
