Repository shipwright-io/build, pull requests merged in 2024-05, with the labels that each got.

#1590 Bump `github.com/docker/docker` dependencies
  go.mod
  go.sum
  vendor/github.com/docker/docker/AUTHORS
  vendor/github.com/docker/docker/pkg/homedir/homedir.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_unix.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_windows.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, kind/dependency-change, release-note-none

#1588 Add StepOutOfMemory as reason for BuildRun failure
  docs/buildrun.md
  pkg/apis/build/v1beta1/buildrun_types.go
  pkg/reconciler/buildrun/resources/conditions.go
  pkg/reconciler/buildrun/resources/conditions_test.go
  pkg/reconciler/buildrun/resources/failure_details.go
  test/integration/buildruns_to_taskruns_test.go
Labels: kind/feature, size/L, lgtm, approved, release-note

#1600 Revisit image tags in BuildAh sample build strategy
  hack/check-latest-images.sh
  samples/v1alpha1/buildstrategy/buildah/buildstrategy_buildah_shipwright_managed_push_cr.yaml
  samples/v1alpha1/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
  samples/v1alpha1/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
  samples/v1beta1/buildstrategy/buildah/buildstrategy_buildah_shipwright_managed_push_cr.yaml
  samples/v1beta1/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
  samples/v1beta1/buildstrategy/source-to-image/buildstrategy_source-to-image-redhat_cr.yaml
Labels: kind/feature, size/XS, lgtm, approved, release-note
