Repository shipwright-io/build, pull requests merged in 2024-11, with the labels that each got.

#1712 Use common test description for Vulnerability Scanning
  cmd/image-processing/main_test.go
  pkg/image/vulnerability_scan_test.go
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#1721 Add total size and total file count to file listing
  pkg/util/filelisting.go
Labels: kind/feature, size/S, lgtm, approved, release-note-none

#1720 Fix nil pointer access in AfterEach of failed e2e test cases
  test/e2e/v1alpha1/common_test.go
  test/e2e/v1beta1/common_test.go
Labels: size/S, lgtm, approved, kind/failing-test, release-note-none

#1719 Install crane binary
  .github/workflows/report-release-vulnerabilities.yaml
Labels: size/XS, lgtm, approved, kind/failing-test, release-note-none

#1710 Update minimum Tekton LTS to v0.56
  .github/workflows/ci.yml
  README.md
Labels: size/XS, lgtm, approved, kind/dependency-change, release-note

#1723 Use specific tag for BuildKit
  docs/buildstrategies.md
  samples/v1alpha1/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/v1beta1/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
Labels: kind/feature, size/XS, lgtm, approved, release-note

#1722 Tweak file listing to omit `.git` directory
  pkg/util/filelisting.go
Labels: size/M, lgtm, approved, kind/cleanup, release-note-none

#1731 Remove usages of "new" as variable name
  pkg/env/env.go
  pkg/volumes/volumes.go
Labels: size/S, lgtm, approved, kind/failing-test, release-note-none

#1730 Remove openshift-ci directory
  openshift-ci/Dockerfile.tools
Labels: size/M, lgtm, approved, kind/cleanup, release-note-none

#1737 Extend Dockerfile based build strategies with target build stage
  samples/v1beta1/buildstrategy/buildah/buildstrategy_buildah_shipwright_managed_push_cr.yaml
  samples/v1beta1/buildstrategy/buildah/buildstrategy_buildah_strategy_managed_push_cr.yaml
  samples/v1beta1/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/v1beta1/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  test/data/v1beta1/build_buildah_cr_target_stage.yaml
  test/data/v1beta1/build_buildkit_cr_target_stage.yaml
  test/data/v1beta1/build_kaniko_cr_target_stage.yaml
  test/data/v1beta1/buildrun_buildah_cr_target_stage.yaml
  test/data/v1beta1/buildrun_buildkit_cr_target_stage.yaml
  test/data/v1beta1/buildrun_kaniko_cr_target_stage.yaml
  test/e2e/v1beta1/e2e_test.go
Labels: kind/feature, size/L, lgtm, approved, release-note
