Repository shipwright-io/build, pull requests merged in 2024-06, with the labels that each got.

#1608 Updates to Owners
  OWNERS
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#1619 Enforce ordered execution of tests
  cmd/image-processing/main_test.go
Labels: size/XS, lgtm, approved, kind/failing-test, release-note-none

#1623 Do not panic if there are no vulnerabilities / Fix severity parsing
  pkg/reconciler/buildrun/resources/results.go
  pkg/reconciler/buildrun/resources/results_test.go
Labels: kind/bug, size/M, lgtm, approved, release-note

#1609 Fix release.yml workflow file
  .github/workflows/release.yaml
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#1620 Refactor/simplify test asset directory look-up
  cmd/image-processing/main_test.go
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#1628 Add legacy endpoints to registry detection
  pkg/image/delete.go
Labels: kind/bug, size/S, lgtm, approved, release-note

#1629 Remove that kaniko-trivy build strategy sample
  .github/workflows/check-latest-images.yaml
  docs/buildstrategies.md
  hack/check-latest-images.sh
  samples/v1alpha1/build/build_kaniko-trivy-bad_cr.yaml
  samples/v1alpha1/build/build_kaniko-trivy-good_cr.yaml
  samples/v1alpha1/buildrun/buildrun_kaniko-trivy-bad_cr.yaml
  samples/v1alpha1/buildrun/buildrun_kaniko-trivy-good_cr.yaml
  samples/v1alpha1/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
  samples/v1alpha1/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
  samples/v1beta1/build/build_kaniko-trivy-bad_cr.yaml
  samples/v1beta1/build/build_kaniko-trivy-good_cr.yaml
  samples/v1beta1/buildrun/buildrun_kaniko-trivy-bad_cr.yaml
  samples/v1beta1/buildrun/buildrun_kaniko-trivy-good_cr.yaml
  samples/v1beta1/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml
  test/e2e/v1alpha1/e2e_test.go
  test/e2e/v1beta1/e2e_test.go
Labels: size/L, lgtm, approved, kind/cleanup, release-note
