Repository shipwright-io/build, pull requests merged in 2025-01, with the labels that each got.

#1766 Change error check in `pkg/git`
  pkg/git/git.go
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#1761 [release-v0.14] Update golang.org/x/net from v0.30.0 to v0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/modules.txt
Labels: size/XS, lgtm, approved, kind/dependency-change, release-note

#1762 Test connectivity to the Git or Registry host before accessing the source
  cmd/bundle/main.go
  cmd/git/main.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/image/endpoint.go
  pkg/image/endpoint_test.go
  pkg/util/tcp.go
  pkg/util/tcp_test.go
  pkg/util/util_suite_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note

#1751 Improve Report release vulnerabilities action
  .github/download-latest-release.sh
  .github/report-release-vulnerabilities.sh
  .github/workflows/report-release-vulnerabilities.yaml
Labels: kind/feature, size/L, lgtm, approved, release-note-none

#1767 Fix action on release vulnerabilities
  .github/report-release-vulnerabilities.sh
  .github/workflows/report-release-vulnerabilities.yaml
Labels: size/S, lgtm, approved, kind/cleanup, release-note-none

#1773 Corrections in vulnerability action triggering new release
  .github/report-release-vulnerabilities.sh
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#1769 Update Calendar and Mailing List
  README.md
Labels: size/S, lgtm, approved, kind/documentation, release-note

#1774 Fix gh command that closes the issue when all vulnerabilities are fixed
  .github/report-release-vulnerabilities.sh
  .github/workflows/report-release-vulnerabilities.yaml
Labels: kind/bug, size/XS, lgtm, approved, release-note-none

#1786 Use ubuntu-latest-16-cores from CNCF for e2e
  .github/workflows/ci.yml
Labels: size/S, lgtm, approved, kind/flake, release-note-none

#1787 Do not use issue search to determine number of issue that was just created
  .github/report-release-vulnerabilities.sh
Labels: kind/bug, size/S, lgtm, release-note-none

#1788 Use Go 1.23 everywhere
  .github/workflows/ci.yml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/report-release-vulnerabilities.yaml
  .github/workflows/update-tekton-version.yaml
  .github/workflows/verify.yaml
  HACK.md
  docs/buildstrategies.md
  samples/v1alpha1/build/build_ko_cr.yaml
  samples/v1alpha1/buildstrategy/ko/buildstrategy_ko_cr.yaml
  samples/v1beta1/build/build_ko_cr.yaml
  samples/v1beta1/buildstrategy/ko/buildstrategy_ko_cr.yaml
Labels: size/S, lgtm, approved, kind/dependency-change, release-note

#1772 Update Readme with new Tags v0.14.1 + v0.14.2
  README.md
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#1776 doc: 2025 Release Schedule
  ROADMAP.md
Labels: size/M, lgtm, approved, kind/documentation, release-note-none
