Repository shipwright-io/build, pull requests merged in 2025-03, with the labels that each got.

#1807 Updates Multi-Arch resources to be ClusterScoped
  docs/buildstrategies.md
  samples/v1beta1/buildstrategy/multiarch-native-buildah/clusterrole_multiarch_native_buildah_cr.yaml
  samples/v1beta1/buildstrategy/multiarch-native-buildah/rolebinding_multiarch_native_buildah_cr.yaml
Labels: size/S, lgtm, approved, release-note-none

#1833 [release-v0.15] Update golang.org/x/net from v0.34.0 to v0.36.0 to address GO-2025-3503
  go.mod
  go.sum
  vendor/golang.org/x/net/context/context.go
  vendor/golang.org/x/net/context/go17.go
  vendor/golang.org/x/net/context/go19.go
  vendor/golang.org/x/net/context/pre_go17.go
  vendor/golang.org/x/net/context/pre_go19.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/internal/httpcommon/ascii.go
  vendor/golang.org/x/net/internal/httpcommon/headermap.go
  vendor/golang.org/x/net/internal/httpcommon/request.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/modules.txt
Labels: size/XS, lgtm, approved, kind/dependency-change, release-note

#1822 Add v0.15.x releases to main
  README.md
Labels: size/S, lgtm, approved, kind/documentation, release-note-none

#1823 Exclude RoleBinding from sample-strategies.yaml
  hack/release.sh
Labels: size/XS, lgtm, approved, kind/cleanup, release-note

#1846 doc: Improve godoc for Source Code Spec
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  pkg/apis/build/v1beta1/buildrun_types.go
  pkg/apis/build/v1beta1/source.go
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#1849 Correct expected value for source.type
  docs/build.md
  pkg/validate/sources.go
  pkg/validate/sources_test.go
Labels: size/S, lgtm, approved, kind/documentation, release-note-none

#1852 Update golang.org/x/net to v0.38.0
  go.mod
  go.sum
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/modules.txt
Labels: size/XS, lgtm, approved, kind/dependency-change, release-note-none
