Repository shipwright-io/build, pull requests merged in 2025-05, with the labels that each got.

#1851 Update Readme with new Tag v0.15.4 / v0.15.5 / v0.15.6 / v0.15.7 / v0.15.8
  README.md
Labels: size/S, lgtm, approved, kind/documentation, release-note-none

#1889 Update Readme with new Tag v0.15.9
  README.md
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#1880 When a full commit SHA is provided as revision, provide it with the git clone command and honor the depth
  cmd/git/main.go
Labels: kind/bug, size/S, lgtm, approved, release-note

#1869 Only cache pods and taskruns with the buildrun label
  pkg/controller/controller.go
Labels: kind/feature, size/M, lgtm, approved, release-note
