Repository shipwright-io/build, pull requests merged in 2025-02, with the labels that each got.

#1711 Add Tolerations to Build and BuildRun objects
  .github/workflows/ci.yml
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  docs/build.md
  docs/buildrun.md
  pkg/apis/build/v1beta1/build_types.go
  pkg/apis/build/v1beta1/buildrun_types.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  pkg/validate/nodeselector.go
  pkg/validate/tolerations.go
  pkg/validate/validate.go
  test/data/v1beta1/build_buildah_tolerations_cr.yaml
  test/data/v1beta1/buildrun_buildah_tolerations_cr.yaml
  test/e2e/v1beta1/e2e_test.go
  test/integration/build_to_taskruns_test.go
  test/integration/buildruns_to_taskruns_test.go
  test/kind/config_three_node.yaml
  test/utils/v1beta1/nodes.go
  test/v1beta1_samples/build_samples.go
  test/v1beta1_samples/buildrun_samples.go
Labels: kind/feature, lgtm, approved, size/XL, release-note

#1796 [1567] Release Workflow Action No Longer Maintained
  .github/workflows/release.yaml
Labels: size/S, lgtm, approved, kind/dependency-change, release-note

#1802 fix: Add Markers and Move Comments for API Docs
  pkg/apis/build/v1beta1/build_types.go
  pkg/apis/build/v1beta1/buildrun_types.go
  pkg/apis/build/v1beta1/buildstrategy_types.go
  pkg/apis/build/v1beta1/clusterbuildstrategy_types.go
  pkg/apis/build/v1beta1/register.go
  pkg/apis/build/v1beta1/trigger.go
  pkg/apis/build/v1beta1/trigger_types.go
  pkg/apis/build/v1beta1/trigger_when.go
Labels: size/M, lgtm, approved, kind/cleanup, release-note-none

#1795 Add v0.14.2 and v0.14.3 and v0.14.4 to readme
  .github/workflows/release.yaml
  README.md
Labels: size/S, lgtm, approved, release-note-none

#1770 Add Custom Scheduler Name to Build and BuildRun objects
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  docs/build.md
  docs/buildrun.md
  pkg/apis/build/v1beta1/build_types.go
  pkg/apis/build/v1beta1/buildrun_types.go
  pkg/reconciler/build/build.go
  pkg/reconciler/build/build_test.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/buildrun_test.go
  pkg/reconciler/buildrun/resources/taskrun.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
  pkg/validate/nodeselector.go
  pkg/validate/nodeselector_test.go
  pkg/validate/scheduler_name.go
  pkg/validate/scheduler_name_test.go
  pkg/validate/tolerations.go
  pkg/validate/tolerations_test.go
  pkg/validate/validate.go
  test/e2e/v1beta1/e2e_test.go
  test/integration/build_to_taskruns_test.go
  test/integration/buildruns_to_taskruns_test.go
  test/v1beta1_samples/build_samples.go
  test/v1beta1_samples/buildrun_samples.go
  test/v1beta1_samples/catalog.go
Labels: kind/feature, lgtm, approved, size/XL, kind/api-change, release-note

#1806 Move seccomp profile definition to container securityContext
  samples/v1alpha1/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
  samples/v1beta1/buildstrategy/buildkit/buildstrategy_buildkit_cr.yaml
Labels: size/S, lgtm, approved, kind/cleanup, release-note

#1811 Update Readme with new Tag v0.15.0
  README.md
Labels: size/S, kind/documentation, release-note-none

#1812 Update golang.org/x/crypto to v0.35.0 to address GO-2025-3487; update golang.org/x/oauth2 to v0.27.0 to address GO-2025-3488
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: size/S, lgtm, approved, kind/dependency-change, release-note-none

#1808 Add dorzel to OWNERS as Reviewer
  OWNERS
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none
