Repository shipwright-io/build, pull requests merged in 2025-07, with the labels that each got.

#1925 feat: Set Field Owners for Build/BuildRun Controllers
  pkg/reconciler/build/build.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrunttlcleanup/buildrun_ttl_cleanup.go
  test/integration/build_to_taskruns_test.go
  test/integration/buildruns_to_taskruns_test.go
Labels: kind/feature, size/M, lgtm, approved, release-note

#1926 feat: Reduce CI Test Matrix Cardinality
  .github/bump-tekton-lts.sh
  .github/workflows/ci.yml
Labels: size/M, lgtm, approved, kind/cleanup, release-note-none

#1929 feat: Update controller image to ubi10
  .ko.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note

#1943 Tweak `check-latest-images.yaml` to use authenticated call
  .github/workflows/check-latest-images.yaml
  hack/check-latest-images.sh
Labels: size/S, lgtm, approved, kind/dependency-change, release-note-none

#1948 Remove `""` from required fields
  deploy/crds/shipwright.io_buildruns.yaml
  deploy/crds/shipwright.io_builds.yaml
  pkg/apis/build/v1alpha1/build_types.go
  pkg/apis/build/v1beta1/build_types.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none

#1899 add labels to isolate features in e2e tests
  test/e2e/v1alpha1/e2e_bundle_test.go
  test/e2e/v1alpha1/e2e_image_mutate_test.go
  test/e2e/v1alpha1/e2e_local_source_upload_test.go
  test/e2e/v1alpha1/e2e_one_off_builds_test.go
  test/e2e/v1alpha1/e2e_params_test.go
  test/e2e/v1alpha1/e2e_rbac_test.go
  test/e2e/v1alpha1/e2e_test.go
  test/e2e/v1beta1/e2e_image_mutate_test.go
  test/e2e/v1beta1/e2e_local_source_upload_test.go
  test/e2e/v1beta1/e2e_ociartifact_test.go
  test/e2e/v1beta1/e2e_one_off_builds_test.go
  test/e2e/v1beta1/e2e_params_test.go
  test/e2e/v1beta1/e2e_rbac_test.go
  test/e2e/v1beta1/e2e_test.go
  test/e2e/v1beta1/e2e_vulnerability_scanning_test.go
Labels: size/L, lgtm, approved, kind/cleanup, release-note-none
