Repository shipwright-io/build, pull requests merged in 2025-08, with the labels that each got.

#1933 Add v0.16 versions to main readme
  README.md
Labels: size/S, lgtm, approved, kind/documentation, release-note-none

#1956 feat(api): Introduce BuildExecutor for multiple runner kinds
  deploy/crds/shipwright.io_buildruns.yaml
  pkg/apis/build/v1beta1/buildrun_conversion.go
  pkg/apis/build/v1beta1/buildrun_types.go
  pkg/apis/build/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/buildrun/buildrun.go
  pkg/reconciler/buildrun/controller.go
  test/utils/v1beta1/lookup.go
  test/v1beta1_samples/catalog.go
Labels: size/M, lgtm, approved, kind/api-change, release-note

#1955 Add volume for trivy
  pkg/reconciler/buildrun/resources/image_processing.go
  pkg/reconciler/buildrun/resources/sources/utils.go
  pkg/reconciler/buildrun/resources/taskrun_test.go
Labels: size/L, lgtm, approved, release-note
